import Image from 'next/image'
import { faqSchema } from '@/lib/seo'
import { images } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { cmsMetadata } from '@/lib/pageMetadata'

const faqs = [{ question: 'Can we hire Cliniq exclusively?', answer: 'Yes. Exclusive venue hire is available depending on date, guest count and programme.' }, { question: 'What kind of events work at Cliniq?', answer: 'Corporate parties, birthdays, bachelor and bachelorette events, student parties, drinks, launches and private club nights.' }, { question: 'Can you arrange DJ, lights and cocktails?', answer: 'Yes. Sound, lighting, DJ options, bar service and cocktails can be included in one proposal.' }]
export async function generateMetadata() { return cmsMetadata('eventSpace', 'en') }
export default function EventSpacePage(){return <><section className="relative min-h-[78vh] pt-36"><Image src={images.crowd} alt="Event space Maastricht venue hire at Cliniq" fill priority sizes="100vw" className="-z-10 object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-burgundy/30"/><div className="container-premium py-24"><p className="eyebrow">Venue hire Maastricht</p><h1 className="h1 mt-5 max-w-5xl">Venue hire with real nightlife energy.</h1><p className="mt-7 max-w-2xl text-xl text-white/70">A premium event space in Maastricht for corporate events, birthdays, private parties, launches and celebrations that need atmosphere.</p><a href="#inquiry" className="btn-primary mt-8">Request proposal</a></div></section><section className="container-premium py-20"><div className="grid gap-4 md:grid-cols-4">{['Corporate event','Birthday','Bachelorette party','Gala','Student party','Private party','Drinks','Product launch'].map(x=><div key={x} className="card rounded-3xl p-6 font-black text-xl">{x}</div>)}</div></section><section id="inquiry" className="container-premium grid gap-8 pb-24 lg:grid-cols-2"><div><p className="eyebrow">Inquiry</p><h2 className="h2 mt-3">Tell us what you are planning.</h2><p className="prose-premium mt-5">Cliniq is built for searches like event space Maastricht, private event Maastricht, venue hire Maastricht and corporate party Maastricht — but the real difference is how the room feels when your guests walk in.</p><div className="mt-8 space-y-4">{faqs.map(f=><details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="event-space" sourcePage="/en/event-space" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'eventType',label:'Event type',options:['Corporate event','Birthday','Bachelorette party','Gala','Student party','Private party','Drinks','Product launch']},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'guests',label:'Guests',type:'number'},{name:'message',label:'Message',required:true}]} /></section><JsonLd data={faqSchema(faqs)} /></>}
