import { faqSchema } from '@/lib/seo'
import { images, imageSets } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { eventSpaceFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
import SafeImage from '@/components/ui/SafeImage'

export async function generateMetadata() { return cmsMetadata('eventSpace', 'en') }
export default function EventSpacePage(){
  const gallery = imageSets.eventSpace.map((url) => ({ url, alt: 'Venue hire Maastricht at CLINIQ' }))
  return <>
    <section className="hero-section relative min-h-[80vh] overflow-hidden pt-36"><SafeImage src={images.redRoom} fallbackSrc={images.fallbackWide} alt="CLINIQ event space with bar and red lighting" fill priority sizes="100vw" className="hero-media -z-10 object-cover brightness-[1.08]" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/62 to-burgundy/10"/><div className="container-premium py-24"><p className="eyebrow mb-4">Events</p><h1 className="h1 max-w-5xl">Hire CLINIQ for your event</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-white/78">A venue in Maastricht with bar, lighting, sound and club atmosphere. Suitable for company parties, birthdays, drinks, bachelor and bachelorette parties and private events.</p><a href="#inquiry" className="btn-primary mt-8">Request proposal</a></div></section>
    <section className="container-premium py-24"><div className="grid gap-6 md:grid-cols-4"><Info title="Capacity" value="Up to about 250 guests" /><Info title="Tech" value="Light and sound" /><Info title="Bar" value="Cocktails and drinks" /><Info title="Location" value="Platielstraat 9A" /></div></section>
    <section className="container-premium grid gap-10 pb-24 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Options</p><h2 className="h2 mt-4">For these events</h2><div className="mt-8 grid gap-4 text-white/72 sm:grid-cols-2"><p>Company parties and drinks.</p><p>Birthdays and private parties.</p><p>Bachelor parties and student nights.</p><p>Product launches and presentations.</p></div></div><div className="grid grid-cols-2 gap-4">{gallery.slice(0,4).map((item,i)=><div key={`${item.url}-${i}`} className={`photo-tile image-frame aspect-[4/5] ${i===0?'row-span-2':''}`}><SafeImage src={item.url} fallbackSrc={images.fallbackWide} alt={item.alt} fill sizes="33vw" className="object-cover brightness-[1.08]" /></div>)}</div></section>
    <section className="container-premium pb-24"><div className="seo-panel grid gap-8 rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 md:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Maastricht</p><h2 className="h2 mt-4">Event space and venue hire in Maastricht</h2></div><p className="text-lg leading-8 text-white/70">CLINIQ is suitable for groups that want to hire a venue in Maastricht without ending up in a standard room. With bar, lighting, sound and dance floor, the space immediately feels like a night out. That makes CLINIQ a strong option for company parties, birthdays, drinks, bachelor and bachelorette parties, student events and other private events in central Maastricht.</p></div></section>
    <section id="inquiry" className="container-premium grid gap-8 pb-24 lg:grid-cols-2"><div><p className="eyebrow">FAQ</p><h2 className="h2 mt-4">Venue questions</h2><div className="faq-grid mt-8 space-y-4">{faqs.map((f)=><details key={f.question} className="luxury-panel rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="event-space" sourcePage="/en/event-space" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'eventType',label:'Event type',options:['Corporate event','Birthday','Bachelorette party','Gala','Student party','Private party','Drinks','Product launch']},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'guests',label:'Guests',type:'number'},{name:'message',label:'Message',required:true}]} /></section><JsonLd data={faqSchema(faqs)} />
  </>
}
function Info({ title, value }: { title: string; value: string }) { return <div className="rounded-[2rem] border border-white/10 bg-white/[0.045] p-7"><p className="eyebrow">{title}</p><p className="mt-4 text-2xl font-black tracking-[-0.04em]">{value}</p></div> }
