import { faqSchema } from '@/lib/seo'
import { images, imageSets } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { eventSpaceFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
import SafeImage from '@/components/ui/SafeImage'

export async function generateMetadata() { return cmsMetadata('eventSpace', 'en') }
const eventTypes = [['Company party','For teams that want a night with bar, music and space to move.'],['Birthday','A private birthday with cocktails, dance floor and a central Maastricht location.'],['Bachelorette party','Easy to combine with cocktails, DJ or a workshop beforehand.'],['Drinks','For groups that want an informal setting without a standard room feel.'],['Private party','Your own night with door policy, bar and a tailored setup.'],['Student event','Suitable for larger groups with music, lighting and clear agreements.'],['Product launch','An atmospheric setting for a presentation, drinks and evening programme.'],['Gala / private night','For a sharper evening with reception, bar and club atmosphere later on.']]
const facilities = [['Bar','A fixed bar setup with team and drinks options.'],['Light and sound','The basis for music, speeches and a full dance floor is already there.'],['DJ options','We can help with DJ, music style and timing.'],['Dance floor','The space feels like a night out, not an empty room.'],['Cocktail options','Cocktails, welcome drinks or drinks packages are possible.'],['Central location','Platielstraat 9A, in the centre of Maastricht.'],['Hospitality team','A team used to busy nights and group events.'],['Cloakroom / lockers','Locker or cloakroom arrangements can be aligned per event.']]

export default function EventSpacePage(){
  const gallery = imageSets.eventSpace.map((url) => ({ url, alt: 'CLINIQ Maastricht event venue' }))
  return <>
    <section className="hero-section relative min-h-[78vh] overflow-hidden pt-36"><SafeImage src={images.redRoom} fallbackSrc={images.fallbackWide} alt="CLINIQ Maastricht event venue with bar and lighting" fill priority sizes="100vw" className="hero-media -z-10 object-cover brightness-[1.08]" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/62 to-burgundy/10"/><div className="container-premium py-24"><p className="eyebrow mb-4">Events</p><h1 className="h1 max-w-5xl">Hire CLINIQ for your event</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-white/78">A venue in Maastricht with bar, lighting, sound and club atmosphere. Suitable for company parties, birthdays, drinks, bachelor and bachelorette parties and private events.</p><a href="#inquiry" className="btn-primary mt-8">Request proposal</a></div></section>
    <section className="container-premium py-24"><p className="eyebrow">Event types</p><h2 className="h2 mt-4">What can you hire CLINIQ for?</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{eventTypes.map(([title,text])=><InfoCard key={title} title={title} text={text} />)}</div></section>
    <section className="container-premium pb-24"><div className="max-w-4xl"><p className="eyebrow">Facilities</p><h2 className="h2 mt-4">What is available?</h2><p className="mt-6 text-lg leading-[1.65] text-white/72 md:text-xl">CLINIQ already has the basis for a complete evening: bar, lighting, sound, dance floor and a team that is used to busy nights.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{facilities.map(([title,text])=><InfoCard key={title} title={title} text={text} />)}</div></section>
    <section className="container-premium pb-24"><div className="seo-panel grid gap-8 rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 md:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Maastricht</p><h2 className="h2 mt-4">Event space and venue hire in Maastricht</h2></div><p className="text-lg leading-[1.65] text-white/72 md:text-xl">CLINIQ is suitable for groups that want to hire a venue in Maastricht without ending up in a standard room. The venue is centrally located on Platielstraat and immediately feels like a night out through the combination of bar, lighting, sound and dance floor. That makes CLINIQ a strong option for company parties, birthdays, drinks, bachelor and bachelorette parties and other private events in central Maastricht. Depending on the date, group size and desired setup, we help shape the evening.</p></div></section>
    <section className="container-premium pb-24"><p className="eyebrow">Images</p><h2 className="h2 mt-4">The space</h2><div className="mt-8 grid auto-rows-[190px] gap-4 md:grid-cols-6 md:auto-rows-[230px]">{gallery.slice(0,5).map((item,i)=><div key={`${item.url}-${i}`} className={`photo-tile image-frame ${i===0?'md:col-span-2 md:row-span-2':'md:col-span-2'}`}><SafeImage src={item.url} fallbackSrc={images.fallbackWide} alt={item.alt} fill sizes="33vw" className="object-cover brightness-[1.08]" /></div>)}</div></section>
    <section className="container-premium pb-24"><p className="eyebrow">FAQ</p><h2 className="h2 mt-4">Frequently asked questions</h2><div className="faq-grid mt-8 grid gap-4 lg:grid-cols-2">{faqs.map((f)=><details key={f.question} className="luxury-panel rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-base leading-7 text-white/72 md:text-lg">{f.answer}</p></details>)}</div></section>
    <section id="inquiry" className="container-premium grid gap-8 pb-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Inquiry</p><h2 className="h2 mt-4">Request proposal</h2><p className="mt-6 text-lg leading-[1.65] text-white/72">Tell us your date, group size and type of event. We will think with you about availability, layout and options.</p></div><InquiryForm type="event-space" sourcePage="/en/event-space" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'eventType',label:'Event type',options:['Corporate event','Birthday','Bachelorette party','Gala','Student party','Private party','Drinks','Product launch']},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'guests',label:'Guests',type:'number'},{name:'message',label:'Message',required:true}]} /></section><JsonLd data={faqSchema(faqs)} />
  </>
}
function InfoCard({ title, text }: { title: string; text: string }) { return <article className="rounded-3xl border border-white/10 bg-white/[0.045] p-5"><h3 className="text-2xl font-black tracking-[-0.035em]">{title}</h3><p className="mt-3 text-white/66">{text}</p></article> }
