import { savePageAction } from '@/lib/admin/actions'
import { readStore } from '@/lib/admin/store'
import MediaUploadField from '@/components/admin/MediaUploadField'
import SafeImage from '@/components/ui/SafeImage'
import { images } from '@/lib/site'

export default async function PagesAdminPage({ searchParams }: { searchParams?: Promise<{ key?: string }> }) {
  const query = await searchParams
  const store = await readStore()
  const page = store.pages.find((item) => item.key === (query?.key || 'home')) || store.pages[0]
  const hero = store.media.find((media) => media.id === page.heroImageId)
  const galleryIds = new Set(page.galleryImageIds || [])
  const hasBlob = Boolean(process.env.BLOB_READ_WRITE_TOKEN)

  return <div className="grid gap-8 xl:grid-cols-[320px_1fr]">
    <aside className="rounded-[2rem] bg-white p-4 shadow-sm"><h2 className="p-2 text-xl font-black">Pages</h2>{store.pages.map((item)=><a key={item.key} href={`/admin/pages?key=${item.key}`} className={`block rounded-2xl p-3 font-bold ${item.key===page.key?'bg-[#f02688] text-white':'hover:bg-black/5'}`}>{item.titleNl}<span className="block text-xs opacity-60">{item.titleEn}</span></a>)}<a href="/admin/seo" className="mt-4 block rounded-2xl bg-black p-3 text-sm font-black uppercase tracking-widest text-white">SEO settings →</a></aside>
    <section className="rounded-[2rem] bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.1em] text-[#f02688]">Page editor</p><h1 className="mt-3 text-4xl font-black tracking-[-0.025em]">{page.titleNl}</h1><div className="mt-5 flex flex-wrap gap-2"><a href="#content" className="rounded-full bg-black px-4 py-2 text-xs font-black uppercase tracking-widest text-white">Content</a><a href="#images" className="rounded-full bg-[#f02688] px-4 py-2 text-xs font-black uppercase tracking-widest text-white">Images</a><a href="/admin/seo" className="rounded-full border border-black/10 px-4 py-2 text-xs font-black uppercase tracking-widest text-black/70">SEO</a></div>{!process.env.BLOB_READ_WRITE_TOKEN ? <p className="mt-4 rounded-2xl bg-yellow-50 p-4 text-sm font-bold text-yellow-800">Uploads are not active yet. Add BLOB_READ_WRITE_TOKEN in Vercel → Project Settings → Environment Variables. After redeploy, drag-and-drop upload will work.</p> : null}
      <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_280px]"><div className="rounded-3xl bg-[#f7f1e7] p-5"><p className="text-xs font-black uppercase tracking-widest text-black/50">Preview</p><h2 className="mt-2 text-3xl font-black">{page.heroTitleNl}</h2><p className="mt-2 text-black/60">{page.heroSubtitleNl}</p></div><div className="relative min-h-48 overflow-hidden rounded-3xl bg-black/10"><SafeImage src={hero?.url} fallbackSrc={images.fallbackWide} alt={hero?.altNl || page.titleNl} fill className="object-cover" objectPosition={hero?.focalPoint || 'center'} /></div></div>
      <form action={savePageAction} className="mt-8 grid gap-6"><input type="hidden" name="key" value={page.key}/>
        <div id="content" className="grid gap-5 lg:grid-cols-2"><div><h2 className="mb-4 text-2xl font-black">Content · Nederlands</h2><Field name="heroTitleNl" label="Hero headline NL" defaultValue={page.heroTitleNl}/><Area name="heroSubtitleNl" label="Hero subtitle NL" defaultValue={page.heroSubtitleNl}/><Area name="bodyNl" label="Section body / SEO copy NL" defaultValue={page.bodyNl}/><Field name="primaryCtaNl" label="Primary CTA NL" defaultValue={page.primaryCtaNl}/><Field name="secondaryCtaNl" label="Secondary CTA NL" defaultValue={page.secondaryCtaNl}/></div><div><h2 className="mb-4 text-2xl font-black">Content · English</h2><Field name="heroTitleEn" label="Hero headline EN" defaultValue={page.heroTitleEn}/><Area name="heroSubtitleEn" label="Hero subtitle EN" defaultValue={page.heroSubtitleEn}/><Area name="bodyEn" label="Section body / SEO copy EN" defaultValue={page.bodyEn}/><Field name="primaryCtaEn" label="Primary CTA EN" defaultValue={page.primaryCtaEn}/><Field name="secondaryCtaEn" label="Secondary CTA EN" defaultValue={page.secondaryCtaEn}/></div></div>
        <div id="images" className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-[#f7f1e7] p-5"><h2 className="mb-3 text-2xl font-black">Images · Upload hero image</h2><p className="mb-4 text-sm text-black/60">The first uploaded image becomes the page hero.</p><MediaUploadField name="heroImageFiles" multiple={false} disabled={!hasBlob} label="Upload new hero image" /></div><div className="rounded-3xl bg-[#f7f1e7] p-5"><h2 className="mb-3 text-2xl font-black">Upload gallery images</h2><p className="mb-4 text-sm text-black/60">New uploads are added to the Media Library and appended to this page gallery.</p><MediaUploadField name="pageImageFiles" disabled={!hasBlob} label="Upload gallery images" /></div></div><div className="grid gap-5"><div className="rounded-3xl border border-black/10 p-5"><h2 className="mb-3 text-2xl font-black">Images · Change hero image</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="flex min-h-24 cursor-pointer items-center justify-center rounded-2xl border border-dashed border-black/20 p-3 text-sm font-black text-black/50"><input type="radio" name="heroImageId" value="" defaultChecked={!page.heroImageId} className="mr-2"/>Default fallback</label>{store.media.map((media)=><label key={media.id} className="group cursor-pointer overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="relative aspect-[4/3]"><SafeImage src={media.url} alt={media.altNl || media.title} fill className="object-cover" objectPosition={media.focalPoint || 'center'} /></div><span className="flex items-center gap-2 p-3 text-xs font-bold"><input type="radio" name="heroImageId" value={media.id} defaultChecked={page.heroImageId===media.id}/>{media.title}</span></label>)}</div></div><div className="rounded-3xl border border-black/10 p-5"><h2 className="mb-3 text-2xl font-black">Images · Add/remove gallery images</h2><p className="mb-4 text-sm text-black/50">Tick images to show on this page. Uploads above are appended automatically.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{store.media.map((media)=><label key={media.id} className="group cursor-pointer overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="relative aspect-[4/3]"><SafeImage src={media.url} alt={media.altNl || media.title} fill className="object-cover" objectPosition={media.focalPoint || 'center'} /></div><span className="flex items-center gap-2 p-3 text-xs font-bold"><input type="checkbox" name="galleryImageIds" value={media.id} defaultChecked={galleryIds.has(media.id)}/>{media.title}</span></label>)}</div></div></div>
        <div className="grid gap-3 sm:grid-cols-3">{[...(page.galleryImageIds || [])].map((id) => { const media=store.media.find((item)=>item.id===id); return media ? <div key={id} className="relative aspect-[4/3] overflow-hidden rounded-2xl"><SafeImage src={media.url} alt={media.altNl || media.title} fill className="object-cover" objectPosition={media.focalPoint || 'center'} /></div> : null })}</div>
        <button className="w-fit rounded-full bg-[#f02688] px-5 py-3 text-sm font-black uppercase tracking-[0.1em] text-white">Save page</button>
      </form>
    </section>
  </div>
}
function Field({ name,label,defaultValue }: { name:string; label:string; defaultValue?:string }) { return <label className="mb-4 grid gap-2 text-sm font-bold">{label}<input name={name} defaultValue={defaultValue||''} className="rounded-2xl border border-black/10 bg-white px-4 py-3" /></label> }
function Area({ name,label,defaultValue }: { name:string; label:string; defaultValue?:string }) { return <label className="mb-4 grid gap-2 text-sm font-bold">{label}<textarea name={name} defaultValue={defaultValue||''} rows={5} className="rounded-2xl border border-black/10 bg-white px-4 py-3" /></label> }
