import Image from 'next/image'
import { readStore } from '@/lib/admin/store'
import { saveEventAction } from '@/lib/admin/actions'
import { images } from '@/lib/site'

export default async function EventsAdminPage({ searchParams }: { searchParams?: Promise<{ edit?: string }> }) {
  const query = await searchParams
  const store = await readStore()
  const edit = store.events.find((event) => event._id === query?.edit)
  return <div className="grid gap-8 xl:grid-cols-[1fr_460px]">
    <section><p className="text-xs font-black uppercase tracking-[0.28em] text-[#f02688]">Agenda</p><h1 className="mt-3 text-5xl font-black tracking-[-0.05em]">Events Manager</h1><div className="mt-8 overflow-hidden rounded-[2rem] bg-white"><table className="w-full text-left text-sm"><thead className="bg-black/[0.04] text-xs uppercase tracking-widest text-black/50"><tr><th className="p-4">Poster</th><th>Event</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>{store.events.map(event=><tr key={event._id} className="border-t border-black/10"><td className="p-4"><div className="relative h-16 w-24 overflow-hidden rounded-xl bg-black/10"><Image src={event.imageUrl || images.club} alt="" fill className="object-cover" /></div></td><td><strong>{event.titleNl || event.title}</strong><p className="text-black/50">{event.ageLimit || '21+'} · {event.startTime}–{event.endTime}</p></td><td>{event.date}</td><td>{event.published === false ? 'Draft' : 'Published'}{event.featured ? ' · Featured' : ''}</td><td><a className="font-black text-[#f02688]" href={`/admin/events?edit=${event._id}`}>Edit</a></td></tr>)}</tbody></table></div></section>
    <aside className="rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">{edit ? 'Edit event' : 'Add event'}</h2><p className="mt-2 text-sm text-black/55">Fast workflow: title, poster, date, publish.</p><form action={saveEventAction} className="mt-6 grid gap-4"><input type="hidden" name="_id" defaultValue={edit?._id} /><Field name="title" label="Internal title" defaultValue={edit?.title} required /><div className="grid grid-cols-2 gap-3"><Field name="date" label="Date" type="date" defaultValue={edit?.date} required /><Field name="ageLimit" label="Minimum age" defaultValue={edit?.ageLimit || '21+'} /></div><div className="grid grid-cols-2 gap-3"><Field name="startTime" label="Opening" defaultValue={edit?.startTime || '22:00'} /><Field name="endTime" label="Closing" defaultValue={edit?.endTime || '03:00'} /></div><label className="grid gap-2 text-sm font-bold">Featured image from Media Library<select name="imageUrl" defaultValue={edit?.imageUrl || ''} className="rounded-2xl border border-black/10 bg-white px-4 py-3"><option value="">Use fallback image</option>{store.media.map((media)=><option key={media.id} value={media.url}>{media.title}</option>)}</select></label><Field name="manualImageUrl" label="Or paste image URL" defaultValue={edit?.imageUrl} /><h3 className="font-black">Nederlands</h3><Field name="titleNl" label="Title NL" defaultValue={edit?.titleNl} /><Field name="subtitleNl" label="Subtitle NL" defaultValue={edit?.subtitleNl} /><Area name="shortDescriptionNl" label="Description NL" defaultValue={edit?.shortDescriptionNl} /><h3 className="font-black">English</h3><Field name="titleEn" label="Title EN" defaultValue={edit?.titleEn} /><Field name="subtitleEn" label="Subtitle EN" defaultValue={edit?.subtitleEn} /><Area name="shortDescriptionEn" label="Description EN" defaultValue={edit?.shortDescriptionEn} /><Field name="ticketUrl" label="Ticket / RSVP link" defaultValue={edit?.ticketUrl} /><label className="flex items-center gap-3 font-bold"><input type="checkbox" name="featured" defaultChecked={edit?.featured} /> Featured</label><label className="flex items-center gap-3 font-bold"><input type="checkbox" name="published" defaultChecked={edit?.published !== false} /> Published</label><button className="rounded-full bg-[#f02688] px-5 py-3 text-sm font-black uppercase tracking-[0.14em] text-white">Save event</button></form></aside>
  </div>
}
function Field({ name, label, defaultValue, type='text', required=false }: { name:string; label:string; defaultValue?:string; type?:string; required?:boolean }) { return <label className="grid gap-2 text-sm font-bold">{label}<input name={name} type={type} defaultValue={defaultValue || ''} required={required} className="rounded-2xl border border-black/10 bg-white px-4 py-3" /></label> }
function Area({ name, label, defaultValue }: { name:string; label:string; defaultValue?:string }) { return <label className="grid gap-2 text-sm font-bold">{label}<textarea name={name} defaultValue={defaultValue || ''} rows={4} className="rounded-2xl border border-black/10 bg-white px-4 py-3" /></label> }
