import Image from 'next/image'
import Link from 'next/link'
import { faqSchema } from '@/lib/seo'
import { images } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { cmsMetadata } from '@/lib/pageMetadata'

const faqs = [{ question: 'Wat kost een cocktail workshop?', answer: 'Standaard vanaf €45 per persoon op basis van drie cocktails. De eigenaar kan prijzen in Sanity aanpassen.' }, { question: 'Wat is de minimale groepsgrootte?', answer: 'De richtlijn is minimaal 15 personen. Kleinere groepen kunnen contact opnemen voor opties.' }, { question: 'Wanneer kan de workshop starten?', answer: 'Meestal donderdag, vrijdag of zaterdag tussen 19:00 en 20:30, in overleg.' }]
export async function generateMetadata() { return cmsMetadata('workshop', 'nl') }
export default function WorkshopPage() { return <>
  <Hero title="Cocktail workshop Maastricht." label="Workshop" image={images.bar} text="Leer shaken met onze bartenders en start jouw avond in premium Cliniq stijl." />
  <section className="container-premium py-20 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Vanaf €45 p.p.</p><h2 className="h2 mt-3">Warm, interactief en gemaakt voor groepen.</h2><p className="prose-premium mt-6">Perfect voor vrijgezellenfeest Maastricht, bedrijfsuitje, verjaardag of vriendengroep. Inclusief uitleg, bar tools, minimaal drie cocktails en optie om na afloop te blijven voor nightlife.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Minimaal 15 personen','3 cocktails inbegrepen','Professionele bartender','Centrum Maastricht'].map((x)=><div className="card rounded-3xl p-6" key={x}><h3 className="font-black text-xl">{x}</h3></div>)}</div></section>
  <section className="container-premium pb-20"><div className="grid gap-4 md:grid-cols-3">{[images.bar, images.hero, images.party].map((src,i)=><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]" key={src}><Image src={src} alt={`Cocktail workshop sfeer ${i+1}`} fill sizes="33vw" className="object-cover" /></div>)}</div></section>
  <section id="form" className="container-premium pb-24 grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Aanvragen</p><h2 className="h2 mt-3">Plan jouw workshop.</h2><div className="mt-8 space-y-4">{faqs.map(f=><details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="workshop" fields={[{name:'name',label:'Naam',required:true},{name:'email',label:'E-mail',type:'email',required:true},{name:'phone',label:'Telefoon'},{name:'preferredDate',label:'Gewenste datum',type:'date'},{name:'groupSize',label:'Groepsgrootte',type:'number'},{name:'message',label:'Bericht',required:true,placeholder:'Vertel ons over je groep en wensen.'}]} /></section><JsonLd data={faqSchema(faqs)} />
</> }
function Hero({title,label,text,image}:{title:string;label:string;text:string;image:string}){return <section className="relative min-h-[72vh] pt-36"><Image src={image} alt={title} fill priority sizes="100vw" className="-z-10 object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-transparent"/><div className="container-premium py-24"><p className="eyebrow">{label}</p><h1 className="h1 mt-5 max-w-4xl">{title}</h1><p className="mt-7 max-w-2xl text-xl text-white/70">{text}</p><Link href="#form" className="btn-primary mt-8">Aanvraag doen</Link></div></section>}
