import Link from 'next/link'
import { readStore } from '@/lib/admin/store'

export default async function AdminDashboard() {
  const store = await readStore()
  const upcoming = store.events.filter((event) => event.published !== false).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5)
  const newLeads = store.leads.filter((lead) => lead.status === 'new')
  return <div>
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.1em] text-[#f02688]">Business operating system</p><h1 className="mt-3 text-5xl font-black tracking-[-0.03em]">Dashboard</h1></div><div className="flex gap-3"><Link className="rounded-full bg-[#f02688] px-5 py-3 text-sm font-black uppercase tracking-[0.1em] text-white" href="/admin/events">Add event</Link><Link className="rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-black uppercase tracking-[0.1em]" href="/admin/media">Upload photos</Link><Link className="rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-black uppercase tracking-[0.1em]" href="/admin/albums">Create album</Link></div></div>
    <div className="mt-8 grid gap-4 md:grid-cols-5">{[['Upcoming events', upcoming.length], ['New leads', newLeads.length], ['Images', store.media.length], ['Albums', store.albums.length], ['Editable pages', store.pages.length]].map(([label,value])=><div key={label} className="rounded-[2rem] bg-white p-6 shadow-sm"><p className="text-sm font-bold text-black/50">{label}</p><p className="mt-3 text-4xl font-black">{value}</p></div>)}</div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">Upcoming events</h2><div className="mt-5 grid gap-3">{upcoming.map(event=><Link href={`/admin/events?edit=${event._id}`} key={event._id} className="rounded-2xl border border-black/10 p-4 hover:border-[#f02688]"><strong>{event.titleNl || event.title}</strong><p className="text-sm text-black/55">{event.date} · {event.startTime || '22:00'} · {event.published === false ? 'Draft' : 'Published'}</p></Link>)}</div></section><section className="rounded-[2rem] bg-white p-6"><h2 className="text-2xl font-black">Recent leads</h2><div className="mt-5 grid gap-3">{store.leads.slice(0,5).map(lead=><Link href="/admin/leads" key={lead.id} className="rounded-2xl border border-black/10 p-4 hover:border-[#f02688]"><strong>{lead.formType} · {lead.name}</strong><p className="text-sm text-black/55">{lead.status} · {lead.email}</p></Link>)}{!store.leads.length ? <p className="text-black/55">No leads yet.</p> : null}</div></section></div>
  </div>
}
