import Link from 'next/link'
import { images, site } from '@/lib/site'
import { getAgendaEvents } from '@/lib/admin/public'
import { EventCard } from '@/components/ui/EventCard'
import SafeImage from '@/components/ui/SafeImage'
import { cmsMetadata } from '@/lib/pageMetadata'
import { ui } from '@/lib/i18n'

export async function generateMetadata() { return cmsMetadata('home', 'en') }

export default async function HomeEn() {
  const t = ui.en
  const events = (await getAgendaEvents()).slice(0, 3)
  const photos = [images.crowd, images.redCrowd, images.party, images.club, images.contactInterior, images.hero]

  return <>
    <section className="hero-section relative min-h-screen overflow-hidden pt-28"><SafeImage src={images.hero} fallbackSrc={images.fallbackHero} alt="CLINIQ Maastricht dance floor with warm light and guests" fill priority sizes="100vw" className="hero-media -z-10 object-cover brightness-[1.08] contrast-[1.04]" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(0,0,0,.84),rgba(0,0,0,.28),rgba(0,0,0,.66)),linear-gradient(0deg,rgba(8,6,7,.96),transparent_42%)]" /><div className="container-premium flex min-h-[calc(100vh-7rem)] items-end pb-20"><div className="reveal max-w-5xl"><p className="eyebrow mb-4">Platielstraat 9A</p><h1 className="h1">CLINIQ Maastricht</h1><p className="mt-5 max-w-3xl text-2xl font-black tracking-[-0.03em] text-white/84 sm:text-4xl">Nightlife, events and workshops on Platielstraat.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link data-track="cta_click" className="btn-primary" href="/en/nightlife">{t.common.viewAgenda}</Link><Link data-track="cta_click" className="btn-secondary" href="/en/event-space">{t.common.requestVenue}</Link></div></div></div></section>
    <NightTicker text="CLINIQ · PLATIELSTRAAT 9A · THURSDAY · FRIDAY · SATURDAY · MUSIC · DRINKS · LATE" />
    <section className="event-section py-24"><div className="container-premium"><SectionIntro eyebrow="Agenda" title="This week at CLINIQ" text="Next nights on Platielstraat." ctaHref="/en/nightlife" ctaLabel={t.common.allEvents} />{events.length ? <div className={`event-grid event-grid-${Math.min(events.length, 3)} mt-10`}>{events.map((event, index) => <EventCard key={event._id} event={event} lang="en" priority={index === 0} />)}</div> : <div className="image-frame mt-10 min-h-[360px] p-8"><SafeImage src={images.club} fallbackSrc={images.fallbackWide} alt="Club night at CLINIQ on Platielstraat" fill sizes="100vw" className="-z-10 object-cover brightness-[1.08]" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-black via-black/45 to-transparent" /><h3 className="h2 absolute bottom-8 left-8 right-8">New events coming soon.</h3></div>}<PhotoStrip photos={photos} href="/en/photos" label="View photos" /></div></section>
    <section className="container-premium pb-24"><SectionIntro eyebrow="Photos" title="Photos from recent nights" text="Browse the atmosphere from club nights, drinks and events at CLINIQ." ctaHref="/en/photos" ctaLabel={t.common.allPhotos} /><div className="mt-10 grid auto-rows-[190px] gap-4 md:grid-cols-6 md:auto-rows-[230px]">{photos.map((src, index) => <Link key={src} href="/en/photos" className={`photo-tile image-frame group rounded-3xl ${index === 0 || index === 5 ? 'md:col-span-2 md:row-span-2' : 'md:col-span-2'}`}><SafeImage src={src} fallbackSrc={images.fallbackWide} alt={`CLINIQ Maastricht atmosphere photo ${index + 1}`} fill sizes="(min-width:768px) 33vw, 100vw" className="object-cover brightness-[1.08] transition duration-700 group-hover:scale-105" /></Link>)}</div><Link href="/en/photos" className="btn-primary mt-8 sm:hidden">{t.common.allPhotos}</Link></section>
    <section className="container-premium space-y-8 pb-24"><ServiceRow href="/en/cocktail-workshop" image={images.workshopBar} eyebrow="Cocktails" title="Cocktail workshop in Maastricht" text="A cocktail workshop at CLINIQ is not a standard drinks table. You step behind the bar, make several cocktails and get guidance from our bartenders. It works well for bachelor and bachelorette parties, team nights, birthdays and groups of friends before or during a night out in Maastricht." cta="View workshop" /><ServiceRow href="/en/event-space" image={images.redRoom} eyebrow="Events" title="Hire CLINIQ for your event" text="CLINIQ is available for drinks, company parties, birthdays, bachelor and bachelorette parties and private events. With bar, lighting, sound and club atmosphere, the venue suits groups looking for a place with character in central Maastricht." cta="View options" reverse /></section>
    <section className="container-premium pb-24"><div className="seo-panel grid gap-8 rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 md:p-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Maastricht</p><h2 className="h2 mt-4">Nightlife, workshops and events in central Maastricht</h2></div><div className="prose-premium"><p>CLINIQ is located on Platielstraat, in the centre of Maastricht. The venue combines a club nights, group nights and event space under one roof. That means you can visit CLINIQ for a night out, a cocktail workshop with a group or a private event. If you are looking for a club in Maastricht, a night out in Maastricht or a venue with more atmosphere than a standard room, CLINIQ is a logical place to start.</p></div></div></section>
    <section className="bg-ivory py-20 text-ink"><div className="container-premium grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><h2 className="text-[40px] font-black leading-none tracking-[-0.055em] sm:text-6xl">CLINIQ Maastricht</h2><p className="mt-5 text-2xl font-bold leading-tight">{site.address.street}. Club nights, groups and events in central Maastricht.</p></div><div className="flex flex-col gap-3 sm:flex-row lg:justify-end"><Link className="btn-primary" href="/en/contact">Contact us</Link><Link className="btn-secondary border-ink/25 bg-ink text-white hover:border-ink hover:bg-ink/90 hover:text-white" href="/en/cocktail-workshop">Request workshop</Link></div></div></section>
  </>
}
function NightTicker({ text }: { text: string }) { return <div className="night-ticker border-y border-white/10 bg-black/35 py-3 text-gold/85"><div className="night-ticker-track"><span>{text}</span><span>{text}</span><span>{text}</span></div></div> }
function PhotoStrip({ photos, href, label }: { photos: string[]; href: string; label: string }) { return <div className="photo-strip mt-14"><div className="photo-strip-grid">{photos.slice(0, 6).map((src, index) => <Link key={`${src}-${index}`} href={href} className={`photo-strip-item group ${index % 3 === 1 ? 'photo-strip-item-tall' : ''}`}><SafeImage src={src} fallbackSrc={images.fallbackWide} alt={`CLINIQ Maastricht atmosphere ${index + 1}`} fill sizes="(min-width:1024px) 16vw, 45vw" className="object-cover brightness-[1.08] transition duration-700 group-hover:scale-105" /></Link>)}</div><Link href={href} className="cta-arrow mt-6 inline-flex text-sm font-black uppercase tracking-[0.18em] text-gold hover:text-white">{label} <span>→</span></Link></div> }

function SectionIntro({ eyebrow, title, text, ctaHref, ctaLabel }: { eyebrow: string; title: string; text: string; ctaHref: string; ctaLabel: string }) { return <div className="reveal-up flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="h2 mt-3">{title}</h2><p className="mt-4 max-w-3xl text-lg leading-[1.65] text-white/70 md:text-xl">{text}</p></div><Link href={ctaHref} className="btn-secondary hidden shrink-0 sm:inline-flex">{ctaLabel}</Link></div> }
function ServiceRow({ href, image, eyebrow, title, text, cta, reverse = false }: { href: string; image: string; eyebrow: string; title: string; text: string; cta: string; reverse?: boolean }) { return <article className="grid overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.045] lg:grid-cols-[45fr_55fr]"><Link href={href} className={`image-frame group min-h-[360px] rounded-none border-0 ${reverse ? 'lg:order-2' : ''}`}><SafeImage src={image} fallbackSrc={images.fallbackWide} alt={title} fill sizes="(min-width:1024px) 45vw, 100vw" className="object-cover brightness-[1.08] transition duration-700 group-hover:scale-105" /></Link><div className="flex flex-col justify-center p-7 md:p-10"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 max-w-3xl text-[32px] font-black leading-tight tracking-[-0.04em] md:text-[42px]">{title}</h2><p className="mt-5 max-w-3xl text-lg leading-[1.65] text-white/72 md:text-xl">{text}</p><Link className="btn-primary mt-8 w-fit" href={href}>{cta}</Link></div></article> }
