import { images, site } from '@/lib/site'
import { contactFaqsEn, contactFaqsNl, eventSpaceFaqsEn, eventSpaceFaqsNl, nightlifeFaqsEn, nightlifeFaqsNl, workshopFaqsEn, workshopFaqsNl } from '@/lib/faqs'
import type { AdminStore } from './types'

const now = '2026-06-04T00:00:00.000Z'

export const defaultStore: AdminStore = {
  media: [
    { id: 'hero', url: images.hero, title: 'Cliniq hero nightlife', altNl: 'Cliniq Maastricht nightlife sfeer', altEn: 'Cliniq Maastricht nightlife atmosphere', usage: ['hero', 'nightlife', 'gallery'], focalPoint: 'center', createdAt: now },
    { id: 'club', url: images.club, title: 'Cliniq club night', altNl: 'Dansvloer bij Cliniq Maastricht', altEn: 'Dance floor at Cliniq Maastricht', usage: ['event poster', 'nightlife', 'gallery'], focalPoint: 'center', createdAt: now },
    { id: 'bar', url: images.bar, title: 'Cliniq cocktail bar', altNl: 'Cocktailbar van Cliniq Maastricht', altEn: 'Cocktail bar at Cliniq Maastricht', usage: ['cocktail workshop', 'bar', 'hero'], focalPoint: 'center', createdAt: now },
    { id: 'crowd', url: images.crowd, title: 'Cliniq event space', altNl: 'Eventruimte met publiek bij Cliniq', altEn: 'Event space with crowd at Cliniq', usage: ['event space', 'hero', 'gallery'], focalPoint: 'center', createdAt: now },
    { id: 'party', url: images.party, title: 'Cliniq party atmosphere', altNl: 'Feest bij Cliniq Maastricht', altEn: 'Party at Cliniq Maastricht', usage: ['nightlife', 'gallery', 'event poster'], focalPoint: 'center', createdAt: now },
  ],
  events: [
    { _id: 'friday-club-night', title: 'Friday Club Night', titleNl: 'Friday Club Night', titleEn: 'Friday Club Night', slug: { current: 'friday-club-night' }, date: '2026-06-12', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'Een stijlvolle clubnacht in hartje Maastricht met cocktails, house, herkenbare hits en Cliniq energie.', shortDescriptionEn: 'A stylish club night in the heart of Maastricht with cocktails, house, familiar hits and Cliniq energy.', featured: true, published: true, imageUrl: images.club, imageAlt: 'Friday Club Night at Cliniq Maastricht' },
    { _id: 'saturday-social', title: 'Saturday Social', titleNl: 'Saturday Social', titleEn: 'Saturday Social', slug: { current: 'saturday-social' }, date: '2026-06-20', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'De zaterdagavond voor groepen, locals en weekendbezoekers die goed willen uitgaan in Maastricht.', shortDescriptionEn: 'The Saturday night for groups, locals and weekend visitors who want a polished Maastricht nightlife experience.', featured: false, published: true, imageUrl: images.party, imageAlt: 'Saturday Social at Cliniq Maastricht' },
  ],
  pages: [
    { key: 'home', titleNl: 'Homepage', titleEn: 'Homepage', heroTitleNl: 'Premium nightlife in Maastricht.', heroTitleEn: 'Premium nightlife in Maastricht.', heroSubtitleNl: 'Een stijlvolle club, cocktailbar en eventlocatie aan de Platielstraat: warm, energiek en gemaakt voor avonden die blijven hangen.', heroSubtitleEn: 'A stylish club, cocktail bar and event venue on Platielstraat: warm, energetic and made for nights people remember.', bodyNl: 'Cliniq brengt club Maastricht, cocktailbar Maastricht en private events samen in één compacte premium locatie.', bodyEn: 'Cliniq brings Maastricht nightlife, cocktail culture and private events together in one premium city-centre venue.', primaryCtaNl: 'Bekijk agenda', primaryCtaEn: 'View agenda', secondaryCtaNl: 'Vraag ruimte aan', secondaryCtaEn: 'Request venue', heroImageId: 'hero', galleryImageIds: ['crowd', 'bar', 'club', 'party'] },
    { key: 'nightlife', titleNl: 'Uitgaan', titleEn: 'Nightlife', heroTitleNl: 'Uitgaan in Maastricht met sfeer.', heroTitleEn: 'Nightlife in Maastricht with atmosphere.', heroSubtitleNl: 'Bekijk de agenda van Cliniq: clubnachten, specials, cocktails en events in hartje Maastricht.', heroSubtitleEn: 'Explore the Cliniq agenda: club nights, specials, cocktails and events in the heart of Maastricht.', bodyNl: 'Voor uitgaan Maastricht zonder anonieme massa: goede ontvangst, sterke bar en muziek die de avond opbouwt.', bodyEn: 'For Maastricht nightlife without the anonymous crowd: warm hosting, a strong bar and music that builds the night.', heroImageId: 'club', galleryImageIds: ['party', 'hero'] },
    { key: 'cocktail-workshop', titleNl: 'Cocktail Workshop', titleEn: 'Cocktail Workshop', heroTitleNl: 'Cocktail workshop Maastricht.', heroTitleEn: 'Cocktail workshop Maastricht.', heroSubtitleNl: 'Shake, stir en proef cocktails in een warme setting die voelt als de start van een goede avond uit.', heroSubtitleEn: 'Shake, stir and taste cocktails in a warm setting that feels like the start of a great night out.', bodyNl: 'Perfect voor vrijgezellenfeest Maastricht, bedrijfsuitje, verjaardag of vriendenweekend.', bodyEn: 'Perfect for bachelorette parties, team events, birthdays and group weekends in Maastricht.', primaryCtaNl: 'Workshop aanvragen', primaryCtaEn: 'Request workshop', heroImageId: 'bar', galleryImageIds: ['hero', 'party'], price: 'Vanaf €45 p.p.', minimumGroupSize: 8 },
    { key: 'event-space', titleNl: 'Event Space', titleEn: 'Event Space', heroTitleNl: 'Ruimte huren in Maastricht met nightlife energie.', heroTitleEn: 'Venue hire in Maastricht with real nightlife energy.', heroSubtitleNl: 'Voor bedrijfsfeest, verjaardag, borrel, vrijgezellenfeest en private events met bar, licht, geluid en een sfeer die direct staat.', heroSubtitleEn: 'For corporate parties, birthdays, drinks, bachelor and bachelorette groups and private events with bar, sound, lights and instant atmosphere.', bodyNl: 'Een feestzaal Maastricht die niet kaal voelt: Cliniq heeft karakter, techniek, bar en hospitality al in huis.', bodyEn: 'A Maastricht event space that never feels empty: Cliniq already has character, sound, bar and hospitality in place.', primaryCtaNl: 'Aanvraag doen', primaryCtaEn: 'Request quote', heroImageId: 'crowd', galleryImageIds: ['club', 'bar', 'party'], capacity: 'Tot circa 250 gasten' },
    { key: 'contact', titleNl: 'Contact', titleEn: 'Contact', heroTitleNl: 'Neem contact op met Cliniq.', heroTitleEn: 'Contact Cliniq.', heroSubtitleNl: 'Voor agenda, workshops, private events, gevonden voorwerpen of algemene vragen.', heroSubtitleEn: 'For agenda questions, workshops, private events, lost property or general questions.' },
    { key: 'jobs', titleNl: 'Vacatures', titleEn: 'Jobs', heroTitleNl: 'Werken bij Cliniq.', heroTitleEn: 'Work at Cliniq.', heroSubtitleNl: 'Word onderdeel van een energiek hospitality team in het hart van Maastricht.', heroSubtitleEn: 'Join an energetic hospitality team in the heart of Maastricht.' },
    { key: 'house-rules', titleNl: 'House Rules', titleEn: 'House Rules', heroTitleNl: 'House rules.', heroTitleEn: 'House rules.', heroSubtitleNl: 'Duidelijke regels voor een veilige, stijlvolle en gastvrije avond.', heroSubtitleEn: 'Clear rules for a safe, stylish and welcoming night.' },
  ],
  faqs: [
    ...workshopFaqsNl.map((item, index) => ({ id: `workshop-nl-${index + 1}`, pageKey: 'cocktail-workshop', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...workshopFaqsEn.map((item, index) => ({ id: `workshop-en-${index + 1}`, pageKey: 'cocktail-workshop', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...eventSpaceFaqsNl.map((item, index) => ({ id: `event-space-nl-${index + 1}`, pageKey: 'event-space', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...eventSpaceFaqsEn.map((item, index) => ({ id: `event-space-en-${index + 1}`, pageKey: 'event-space', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...nightlifeFaqsNl.map((item, index) => ({ id: `nightlife-nl-${index + 1}`, pageKey: 'nightlife', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...nightlifeFaqsEn.map((item, index) => ({ id: `nightlife-en-${index + 1}`, pageKey: 'nightlife', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...contactFaqsNl.map((item, index) => ({ id: `contact-nl-${index + 1}`, pageKey: 'contact', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...contactFaqsEn.map((item, index) => ({ id: `contact-en-${index + 1}`, pageKey: 'contact', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
  ],
  seo: [],
  leads: [],
  jobs: [{ _id: 'open', title: 'Open sollicitatie', type: 'Parttime', description: 'Wij zoeken hospitality talent voor bar, floor en events.', requirements: ['Gastvrij', 'Beschikbaar in avonden/weekenden', 'Teamspeler'], published: true }],
  settings: { phone: site.phone, email: site.email, whatsapp: site.whatsapp, address: `${site.address.street}, ${site.address.postalCode} ${site.address.city}`, openingHours: site.hours, instagram: site.instagram, tiktok: site.tiktok },
  analytics: [],
}
