import { images, site } from '@/lib/site'
import { contactFaqsEn, contactFaqsNl, eventSpaceFaqsEn, eventSpaceFaqsNl, nightlifeFaqsEn, nightlifeFaqsNl, workshopFaqsEn, workshopFaqsNl } from '@/lib/faqs'
import type { AdminStore } from './types'

const now = '2026-06-04T00:00:00.000Z'

export const defaultStore: AdminStore = {
  media: [
    { id: 'hero', url: images.hero, title: 'Hero nightlife crowd', altNl: 'Publiek op de dansvloer van CLINIQ Maastricht met warm licht', altEn: 'Crowd on the CLINIQ Maastricht dance floor with warm lighting', usage: ['hero', 'nightlife', 'crowd', 'gallery'], recommendedPageUsage: ['home', 'nightlife'], fallbackPriority: 1, focalPoint: 'center', createdAt: now },
    { id: 'red-crowd', url: images.redCrowd, title: 'Blue red fog crowd', altNl: 'Drukke clubavond bij CLINIQ met rood en blauw licht', altEn: 'Busy CLINIQ club night with red and blue lighting', usage: ['nightlife', 'crowd', 'gallery', 'event poster'], recommendedPageUsage: ['nightlife', 'albums'], fallbackPriority: 2, focalPoint: 'center', createdAt: now },
    { id: 'red-room', url: images.redRoom, title: 'Red bar room', altNl: 'CLINIQ bar en dansvloer met rode verlichting', altEn: 'CLINIQ bar and dance floor with red lighting', usage: ['event-space', 'bar', 'gallery'], recommendedPageUsage: ['event-space', 'home'], fallbackPriority: 3, focalPoint: 'center', createdAt: now },
    { id: 'workshop-bar', url: images.workshopBar, title: 'Cocktail workshop behind the bar', altNl: 'Gasten maken cocktails achter de bar bij CLINIQ Maastricht', altEn: 'Guests making cocktails behind the bar at CLINIQ Maastricht', usage: ['cocktail', 'workshop', 'bar', 'hero'], recommendedPageUsage: ['cocktail-workshop'], fallbackPriority: 4, focalPoint: 'center', createdAt: now },
    { id: 'mojito', url: images.mojito, title: 'Mojito cocktail', altNl: 'Mojito cocktail met limoen en munt bij CLINIQ', altEn: 'Mojito cocktail with lime and mint at CLINIQ', usage: ['cocktail', 'workshop', 'bar', 'gallery'], recommendedPageUsage: ['cocktail-workshop'], fallbackPriority: 5, focalPoint: 'center', createdAt: now },
    { id: 'espresso', url: images.espresso, title: 'Espresso martini cocktail', altNl: 'Cocktail in coupeglas op de bar van CLINIQ', altEn: 'Cocktail in a coupe glass on the CLINIQ bar', usage: ['cocktail', 'bar', 'gallery'], recommendedPageUsage: ['cocktail-workshop'], fallbackPriority: 6, focalPoint: 'center', createdAt: now },
    { id: 'passion', url: images.passion, title: 'Passion fruit cocktail', altNl: 'Passievrucht cocktail bij CLINIQ Maastricht', altEn: 'Passion fruit cocktail at CLINIQ Maastricht', usage: ['cocktail', 'workshop', 'gallery'], recommendedPageUsage: ['cocktail-workshop'], fallbackPriority: 7, focalPoint: 'center', createdAt: now },
    { id: 'contact-interior', url: images.contactInterior, title: 'CLINIQ interior bar detail', altNl: 'Interieur van CLINIQ Maastricht met bar en warm licht', altEn: 'CLINIQ Maastricht interior with bar and warm light', usage: ['contact', 'event-space', 'bar', 'gallery'], recommendedPageUsage: ['contact', 'event-space'], fallbackPriority: 8, focalPoint: 'center', createdAt: now },
    { id: 'footer-logo', url: images.footerLogo, title: 'CLINIQ Maastricht logo', altNl: 'CLINIQ Maastricht logo', altEn: 'CLINIQ Maastricht logo', usage: ['contact', 'gallery'], recommendedPageUsage: ['contact'], fallbackPriority: 11, focalPoint: 'center', createdAt: now },
    { id: 'club', url: images.club, title: 'CLINIQ club night', altNl: 'Dansvloer bij CLINIQ Maastricht', altEn: 'Dance floor at CLINIQ Maastricht', usage: ['event poster', 'nightlife', 'gallery'], recommendedPageUsage: ['nightlife'], fallbackPriority: 9, focalPoint: 'center', createdAt: now },
    { id: 'party', url: images.party, title: 'Warm party atmosphere', altNl: 'Feestavond bij CLINIQ Maastricht', altEn: 'Party night at CLINIQ Maastricht', usage: ['nightlife', 'gallery', 'event poster'], recommendedPageUsage: ['home', 'albums'], fallbackPriority: 10, focalPoint: 'center', createdAt: now },
  ],
  events: [
    { _id: 'friday-club-night', title: 'Friday Club Night', titleNl: 'Friday Club Night', titleEn: 'Friday Club Night', slug: { current: 'friday-club-night' }, date: '2026-06-12', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'Een stijlvolle clubnacht in hartje Maastricht met cocktails, house, herkenbare hits en Cliniq energie.', shortDescriptionEn: 'A stylish club night in the heart of Maastricht with cocktails, house, familiar hits and Cliniq energy.', featured: true, published: true, imageUrl: images.club, imageAlt: 'Friday Club Night at CLINIQ Maastricht' },
    { _id: 'saturday-social', title: 'Saturday Social', titleNl: 'Saturday Social', titleEn: 'Saturday Social', slug: { current: 'saturday-social' }, date: '2026-06-20', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'De zaterdagavond voor groepen, locals en weekendbezoekers die goed willen uitgaan in Maastricht.', shortDescriptionEn: 'A Saturday night for groups, locals and weekend visitors who want cocktails, music and a well-run room in Maastricht.', featured: false, published: true, imageUrl: images.party, imageAlt: 'Saturday Social at CLINIQ Maastricht' },
  ],
  pages: [
    { key: 'home', titleNl: 'Homepage', titleEn: 'Homepage', heroTitleNl: 'CLINIQ Maastricht', heroTitleEn: 'CLINIQ Maastricht', heroSubtitleNl: 'Club, cocktailbar en eventlocatie aan de Platielstraat. Voor avonden met goede muziek, sterke cocktails en precies de juiste sfeer.', heroSubtitleEn: 'Club, cocktail bar and event venue on Platielstraat. Built for good music, strong cocktails and nights with the right kind of energy.', bodyNl: 'Aan de Platielstraat komen muziek, bar en mensen dicht bij elkaar. Geen grootse belofte, gewoon een ruimte die klopt zodra de avond loskomt.', bodyEn: 'On Platielstraat, music, bar and people sit close together. No empty promise: just a room that works the moment the night starts moving.', primaryCtaNl: 'Bekijk agenda', primaryCtaEn: 'View agenda', secondaryCtaNl: 'Ruimte huren', secondaryCtaEn: 'Hire the venue', heroImageId: 'hero', galleryImageIds: ['red-crowd', 'workshop-bar', 'red-room', 'party'] },
    { key: 'nightlife', titleNl: 'Uitgaan', titleEn: 'Nightlife', heroTitleNl: 'Uitgaan bij CLINIQ', heroTitleEn: 'Nightlife at CLINIQ', heroSubtitleNl: 'Elke donderdag, vrijdag en zaterdag verandert CLINIQ in een clubavond met cocktails, DJ’s en een volwassen sfeer midden in Maastricht. Check de agenda, kom op tijd en neem je ID mee.', heroSubtitleEn: 'Every Thursday, Friday and Saturday, CLINIQ turns into a club night with cocktails, DJs and a grown-up atmosphere in the centre of Maastricht. Check the agenda, arrive on time and bring your ID.', bodyNl: 'Voor uitgaan Maastricht zonder anonieme massa: goede ontvangst, sterke bar en muziek die de avond opbouwt.', bodyEn: 'For Maastricht nightlife without the anonymous crowd: warm hosting, a strong bar and music that builds the night.', heroImageId: 'red-crowd', galleryImageIds: ['hero', 'club', 'party'] },
    { key: 'cocktail-workshop', titleNl: 'Cocktail Workshop', titleEn: 'Cocktail Workshop', heroTitleNl: 'Cocktail workshop bij CLINIQ', heroTitleEn: 'Cocktail workshop at CLINIQ', heroSubtitleNl: 'Geen standaard borrel, maar samen achter de bar. Tijdens de cocktail workshop maak je meerdere cocktails onder begeleiding van onze bartenders. Ideaal voor vrijgezellenfeesten, bedrijfsuitjes, verjaardagen en vriendengroepen.', heroSubtitleEn: 'Not a standard drinks table, but a place behind the bar. During the workshop, you make several cocktails with guidance from our bartenders. Ideal for bachelor and bachelorette parties, team nights, birthdays and groups of friends.', bodyNl: 'Perfect voor vrijgezellenfeest Maastricht, bedrijfsuitje, verjaardag of vriendenweekend.', bodyEn: 'Perfect for bachelorette parties, team events, birthdays and group weekends in Maastricht.', primaryCtaNl: 'Workshop aanvragen', primaryCtaEn: 'Request workshop', heroImageId: 'workshop-bar', galleryImageIds: ['mojito', 'espresso', 'passion'], price: 'Vanaf €45 p.p.', minimumGroupSize: 8 },
    { key: 'event-space', titleNl: 'Event Space', titleEn: 'Event Space', heroTitleNl: 'Ruimte huren bij CLINIQ', heroTitleEn: 'Hire CLINIQ for your event', heroSubtitleNl: 'Zoek je een feestlocatie in Maastricht die niet aanvoelt als een standaard zaal? CLINIQ is geschikt voor bedrijfsfeesten, verjaardagen, borrels, vrijgezellenfeesten en private events met bar, licht, geluid en clubgevoel.', heroSubtitleEn: 'Looking for a venue in Maastricht that does not feel like a standard room? CLINIQ works for company parties, birthdays, drinks, bachelor and bachelorette parties and private events with bar, lighting, sound and club atmosphere.', bodyNl: 'Een feestzaal Maastricht die niet kaal voelt: CLINIQ heeft karakter, techniek, bar en hospitality al in huis.', bodyEn: 'A Maastricht event space that never feels empty: CLINIQ already has character, sound, bar and hospitality in place.', primaryCtaNl: 'Aanvraag doen', primaryCtaEn: 'Request quote', heroImageId: 'red-room', galleryImageIds: ['contact-interior', 'red-crowd', 'bar'], capacity: 'Tot circa 250 gasten' },
    { key: 'contact', titleNl: 'Contact', titleEn: 'Contact', heroTitleNl: 'Contact', heroTitleEn: 'Contact', heroSubtitleNl: 'Vragen over de agenda, een cocktail workshop of het huren van CLINIQ? Neem contact met ons op. Je vindt ons aan de Platielstraat 9A, midden in Maastricht.', heroSubtitleEn: 'Questions about the agenda, a cocktail workshop or hiring CLINIQ for your event? Contact us. You’ll find us at Platielstraat 9A in the centre of Maastricht.', heroImageId: 'contact-interior', galleryImageIds: ['bar', 'footer-logo'] },
    { key: 'jobs', titleNl: 'Vacatures', titleEn: 'Jobs', heroTitleNl: 'Werken waar de avond beweegt.', heroTitleEn: 'Work where the night moves.', heroSubtitleNl: 'Word onderdeel van een energiek hospitality team in het hart van Maastricht.', heroSubtitleEn: 'Join an energetic hospitality team in the heart of Maastricht.' },
    { key: 'house-rules', titleNl: 'House Rules', titleEn: 'House Rules', heroTitleNl: 'Duidelijk aan de deur. Relaxed binnen.', heroTitleEn: 'Clear at the door. Easy inside.', heroSubtitleNl: 'Duidelijke regels voor een veilige, stijlvolle en gastvrije avond.', heroSubtitleEn: 'Clear rules for a safe, stylish and welcoming night.' },
  ],
  faqs: [
    ...workshopFaqsNl.map((item, index) => ({ id: `workshop-nl-${index + 1}`, pageKey: 'cocktail-workshop', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...workshopFaqsEn.map((item, index) => ({ id: `workshop-en-${index + 1}`, pageKey: 'cocktail-workshop', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...eventSpaceFaqsNl.map((item, index) => ({ id: `event-space-nl-${index + 1}`, pageKey: 'event-space', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...eventSpaceFaqsEn.map((item, index) => ({ id: `event-space-en-${index + 1}`, pageKey: 'event-space', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...nightlifeFaqsNl.map((item, index) => ({ id: `nightlife-nl-${index + 1}`, pageKey: 'nightlife', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...nightlifeFaqsEn.map((item, index) => ({ id: `nightlife-en-${index + 1}`, pageKey: 'nightlife', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...contactFaqsNl.map((item, index) => ({ id: `contact-nl-${index + 1}`, pageKey: 'contact', language: 'nl' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
    ...contactFaqsEn.map((item, index) => ({ id: `contact-en-${index + 1}`, pageKey: 'contact', language: 'en' as const, question: item.question, answer: item.answer, published: true, order: index + 1 })),
  ],
  albums: [
    { id: 'friday-club-night-album', slug: 'friday-club-night-12-june', titleNl: 'Friday Club Night — 12 juni', titleEn: 'Friday Club Night — 12 June', date: '2026-06-12', relatedEventId: 'friday-club-night', coverImageId: 'red-crowd', imageIds: ['red-crowd', 'hero', 'party', 'red-room'], published: true, descriptionNl: 'Crowd, licht en late energie aan de Platielstraat. Een album voor iedereen die erbij was — en voor iedereen die de sfeer rustig wil terugzien.', descriptionEn: 'Crowd, light and late-night energy on Platielstraat. An album for everyone who was there — and anyone who wants to see the room again.', createdAt: now },
    { id: 'cocktail-workshop-album', slug: 'cocktail-workshop-maastricht', titleNl: 'Cocktail workshops bij CLINIQ', titleEn: 'Cocktail workshops at CLINIQ', date: '2026-06-04', coverImageId: 'workshop-bar', imageIds: ['workshop-bar', 'mojito', 'espresso', 'passion'], published: true, descriptionNl: 'Shakers, glaswerk, cocktails en groepsenergie: zo voelt een workshop bij CLINIQ wanneer de avond nog maar net begint.', descriptionEn: 'Shakers, glassware, cocktails and group energy: this is what a Cliniq workshop feels like before the night fully starts.', createdAt: now },
  ],
  seo: [],
  leads: [],
  jobs: [{ _id: 'open', title: 'Open sollicitatie', type: 'Parttime', description: 'Wij zoeken hospitality talent voor bar, floor en events.', requirements: ['Gastvrij', 'Beschikbaar in avonden/weekenden', 'Teamspeler'], published: true }],
  settings: { phone: site.phone, email: site.email, whatsapp: site.whatsapp, address: `${site.address.street}, ${site.address.postalCode} ${site.address.city}`, openingHours: site.hours, instagram: site.instagram, tiktok: site.tiktok },
  analytics: [],
}
