import { images, site } from '@/lib/site'
import type { AdminStore } from './types'

const now = '2026-06-04T00:00:00.000Z'

export const defaultStore: AdminStore = {
  media: [
    { id: 'hero', url: images.hero, title: 'Cliniq hero nightlife', altNl: 'Cliniq Maastricht nightlife sfeer', altEn: 'Cliniq Maastricht nightlife atmosphere', usage: ['homepage hero', 'nightlife'], createdAt: now },
    { id: 'club', url: images.club, title: 'Cliniq club night', altNl: 'Dansvloer bij Cliniq Maastricht', altEn: 'Dance floor at Cliniq Maastricht', usage: ['event fallback', 'nightlife'], createdAt: now },
    { id: 'bar', url: images.bar, title: 'Cliniq cocktail bar', altNl: 'Cocktailbar van Cliniq Maastricht', altEn: 'Cocktail bar at Cliniq Maastricht', usage: ['workshop', 'bar'], createdAt: now },
    { id: 'crowd', url: images.crowd, title: 'Cliniq event space', altNl: 'Eventruimte met publiek bij Cliniq', altEn: 'Event space with crowd at Cliniq', usage: ['event space'], createdAt: now },
    { id: 'party', url: images.party, title: 'Cliniq party atmosphere', altNl: 'Feest bij Cliniq Maastricht', altEn: 'Party at Cliniq Maastricht', usage: ['gallery'], createdAt: now },
  ],
  events: [
    { _id: 'friday-club-night', title: 'Friday Club Night', titleNl: 'Friday Club Night', titleEn: 'Friday Club Night', slug: { current: 'friday-club-night' }, date: '2026-06-12', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'Een stijlvolle clubnacht in hartje Maastricht met cocktails, house, herkenbare hits en Cliniq energie.', shortDescriptionEn: 'A stylish club night in the heart of Maastricht with cocktails, house, familiar hits and Cliniq energy.', featured: true, published: true, imageUrl: images.club, imageAlt: 'Friday Club Night at Cliniq Maastricht' },
    { _id: 'saturday-social', title: 'Saturday Social', titleNl: 'Saturday Social', titleEn: 'Saturday Social', slug: { current: 'saturday-social' }, date: '2026-06-20', startTime: '22:00', endTime: '03:00', ageLimit: '21+', shortDescriptionNl: 'De zaterdagavond voor groepen, locals en weekendbezoekers die goed willen uitgaan in Maastricht.', shortDescriptionEn: 'The Saturday night for groups, locals and weekend visitors who want a polished Maastricht nightlife experience.', featured: false, published: true, imageUrl: images.party, imageAlt: 'Saturday Social at Cliniq Maastricht' },
  ],
  pages: [
    { key: 'home', titleNl: 'Homepage', titleEn: 'Homepage', heroTitleNl: 'Premium nightlife in Maastricht.', heroTitleEn: 'Premium nightlife in Maastricht.', heroSubtitleNl: 'Cliniq Maastricht is de stijlvolle club, cocktailbar en eventlocatie in het hart van de stad — gebouwd voor avonden die blijven hangen.', heroSubtitleEn: 'Cliniq Maastricht is a stylish club, cocktail bar and event venue in the city centre — made for nights people remember.', heroImageId: 'hero' },
    { key: 'nightlife', titleNl: 'Uitgaan', titleEn: 'Nightlife', heroTitleNl: 'Uitgaan in Maastricht met sfeer.', heroTitleEn: 'Nightlife in Maastricht with atmosphere.', heroSubtitleNl: 'Bekijk de agenda van Cliniq: clubnachten, specials en events in hartje Maastricht.', heroSubtitleEn: 'Explore the Cliniq agenda: club nights, specials and events in the heart of Maastricht.', heroImageId: 'club' },
    { key: 'cocktail-workshop', titleNl: 'Cocktail Workshop', titleEn: 'Cocktail Workshop', heroTitleNl: 'Cocktail workshop Maastricht.', heroTitleEn: 'Cocktail workshop Maastricht.', heroSubtitleNl: 'Shake, stir en proef cocktails in een warme setting die voelt als de start van een goede avond uit.', heroSubtitleEn: 'Shake, stir and taste cocktails in a warm setting that feels like the start of a great night out.', heroImageId: 'bar', price: 'Vanaf €45 p.p.', minimumGroupSize: 8 },
    { key: 'event-space', titleNl: 'Event Space', titleEn: 'Event Space', heroTitleNl: 'Ruimte huren in Maastricht met nightlife energie.', heroTitleEn: 'Venue hire in Maastricht with real nightlife energy.', heroSubtitleNl: 'Voor bedrijfsfeest, verjaardag, borrel, vrijgezellenfeest en private events met bar, licht en geluid.', heroSubtitleEn: 'For corporate parties, birthdays, drinks, bachelor and bachelorette groups and private events with bar, sound and lights.', heroImageId: 'crowd', capacity: 'Tot circa 250 gasten' },
    { key: 'contact', titleNl: 'Contact', titleEn: 'Contact', heroTitleNl: 'Neem contact op met Cliniq.', heroTitleEn: 'Contact Cliniq.', heroSubtitleNl: 'Voor agenda, workshops, private events, gevonden voorwerpen of algemene vragen.', heroSubtitleEn: 'For agenda questions, workshops, private events, lost property or general questions.' },
    { key: 'jobs', titleNl: 'Vacatures', titleEn: 'Jobs', heroTitleNl: 'Werken bij Cliniq.', heroTitleEn: 'Work at Cliniq.', heroSubtitleNl: 'Word onderdeel van een energiek hospitality team in het hart van Maastricht.', heroSubtitleEn: 'Join an energetic hospitality team in the heart of Maastricht.' },
    { key: 'house-rules', titleNl: 'House Rules', titleEn: 'House Rules', heroTitleNl: 'House rules.', heroTitleEn: 'House rules.', heroSubtitleNl: 'Duidelijke regels voor een veilige, stijlvolle en gastvrije avond.', heroSubtitleEn: 'Clear rules for a safe, stylish and welcoming night.' },
  ],
  faqs: [
    { id: 'workshop-included-nl', pageKey: 'cocktail-workshop', language: 'nl', question: 'Wat zit er inbegrepen bij de cocktail workshop?', answer: 'Tijdens de cocktail workshop leer je stap voor stap hoe je goede cocktails maakt. Onze bartender legt uit hoe je smaken balanceert, hoe je werkt met shakers, ijs, garnering en glaswerk, en waarom kleine details veel verschil maken. Afhankelijk van het arrangement maak je meerdere cocktails zelf en proef je tussendoor wat je maakt. De workshop vindt plaats in de sfeer van Cliniq, waardoor het geen standaard cursus voelt maar een gezellige start van een avond uit in Maastricht.', published: true, order: 1 },
    { id: 'workshop-groups-nl', pageKey: 'cocktail-workshop', language: 'nl', question: 'Voor welke groepen is de workshop geschikt?', answer: 'De workshop is geschikt voor vriendengroepen, vrijgezellenfeesten, bedrijfsuitjes, verjaardagen en studentengroepen die iets willen doen vóór het uitgaan. Beginners zijn juist welkom: je hoeft geen ervaring te hebben, want onze bartender begeleidt de groep op een toegankelijke manier. Voor grotere groepen stemmen we tempo, opstelling en drankkeuze vooraf af.', published: true, order: 2 },
    { id: 'venue-events-nl', pageKey: 'event-space', language: 'nl', question: 'Welke events kan ik bij Cliniq organiseren?', answer: 'Cliniq is geschikt voor bedrijfsfeesten, verjaardagen, borrels, vrijgezellenfeesten, studentenfeesten, product launches, private parties en kleinere gala-avonden. De ruimte heeft het voordeel van een echte nightlife setting: bar, licht, geluid en sfeer zijn al aanwezig. Daardoor voelt een event meteen minder kaal dan een standaard zaal.', published: true, order: 1 },
    { id: 'nightlife-age-nl', pageKey: 'nightlife', language: 'nl', question: 'Wat is de minimumleeftijd?', answer: 'De minimumleeftijd kan per avond verschillen en staat vermeld bij het event in de agenda. Neem altijd een geldig identiteitsbewijs mee. Bij twijfel of drukte kan de deur een extra controle uitvoeren, zodat de avond veilig en prettig blijft voor alle gasten.', published: true, order: 1 },
    { id: 'contact-fast-nl', pageKey: 'contact', language: 'nl', question: 'Wat is de snelste manier om contact op te nemen?', answer: 'Voor boekingen, workshops en private events is het contactformulier het handigst, omdat je dan meteen alle belangrijke informatie kunt meesturen. Voor korte vragen kun je bellen of mailen. Vermeld bij eventaanvragen altijd datum, aantal gasten, type event en eventuele wensen.', published: true, order: 1 },
  ],
  seo: [],
  leads: [],
  jobs: [{ _id: 'open', title: 'Open sollicitatie', type: 'Parttime', description: 'Wij zoeken hospitality talent voor bar, floor en events.', requirements: ['Gastvrij', 'Beschikbaar in avonden/weekenden', 'Teamspeler'], published: true }],
  settings: { phone: site.phone, email: site.email, whatsapp: site.whatsapp, address: `${site.address.street}, ${site.address.postalCode} ${site.address.city}`, openingHours: site.hours, instagram: site.instagram, tiktok: site.tiktok },
  analytics: [],
}
