import { readStore } from '@/lib/admin/store'
import { updateLeadStatusAction } from '@/lib/admin/actions'

export default async function LeadsAdminPage() {
  const store = await readStore()
  const leads = store.leads.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))
  return <div><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.28em] text-[#f02688]">Forms</p><h1 className="mt-3 text-5xl font-black tracking-[-0.05em]">Leads</h1><p className="mt-3 max-w-2xl text-black/60">All contact, workshop, event-space and job submissions are stored here with source page, requested date and status.</p></div><a href={`/api/leads/export?token=${process.env.LEADS_EXPORT_TOKEN || 'SET_TOKEN'}`} className="rounded-full bg-[#f02688] px-5 py-3 text-sm font-black uppercase tracking-[0.14em] text-white">Export CSV</a></div>
    <div className="mt-8 grid gap-4">{leads.map((lead)=>{ const payload=lead.payload || {}; const requestedDate=String(payload.preferredDate || payload.date || ''); return <article key={lead.id} className="rounded-[2rem] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><p className="text-sm font-black uppercase tracking-widest text-[#f02688]">{lead.formType} · {lead.status}</p><h2 className="mt-2 text-2xl font-black">{lead.name}</h2><p className="text-black/60">{lead.email} · {lead.phone || 'No phone'}</p>{requestedDate ? <p className="mt-2 rounded-full bg-[#f7f1e7] px-3 py-1 text-sm font-bold text-black/70">Requested date: {requestedDate}</p> : null}<p className="mt-4 max-w-3xl leading-7 text-black/70">{lead.message}</p><p className="mt-2 text-xs text-black/40">{lead.createdAt} · {lead.sourcePage}</p></div><form action={updateLeadStatusAction} className="flex items-start gap-2"><input type="hidden" name="id" value={lead.id}/><select name="status" defaultValue={lead.status} className="rounded-2xl border border-black/10 bg-white px-4 py-3"><option value="new">New</option><option value="contacted">Contacted</option><option value="handled">Handled</option><option value="archived">Archived</option></select><button className="rounded-full bg-black px-4 py-3 text-xs font-black uppercase tracking-widest text-white">Save</button></form></div></article>})}{!leads.length ? <p className="rounded-[2rem] bg-white p-8 text-black/55">No submissions yet.</p> : null}</div></div>
}
