import { faqSchema } from '@/lib/seo'
import { images, imageSets } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { workshopFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
import SafeImage from '@/components/ui/SafeImage'
import { SEO_TEXT } from '@/lib/content'

export async function generateMetadata() { return cmsMetadata('workshop', 'en') }
const groupTypes = ['Bachelorette party', 'Company outing', 'Birthday', 'Friends group', 'Team night', 'Before going out']

export default function WorkshopPageEn(){
  const gallery = imageSets.workshop.map((url) => ({ url, alt: 'Cocktail workshop at CLINIQ Maastricht' }))
  return <>
    <section className="hero-section relative min-h-[78vh] overflow-hidden pt-36"><SafeImage src={images.workshopBar} fallbackSrc={images.fallbackWide} alt="Cocktail workshop at CLINIQ Maastricht behind the bar" fill priority sizes="100vw" className="hero-media -z-10 object-cover brightness-[1.08]" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/58 to-black/18"/><div className="container-premium py-24"><p className="eyebrow mb-4">Cocktail bar</p><h1 className="h1 max-w-5xl">Cocktail workshop at CLINIQ</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-white/78">For groups of 15 or more. Make cocktails, then stay for the night.</p><a href="#inquiry" className="btn-primary mt-8">Request workshop</a></div></section>
    <section className="container-premium py-24"><div className="grid gap-4 md:grid-cols-4"><Fact title="€15 per cocktail" text="Including several cocktails, materials and guidance." /><Fact title="Minimum 15 guests" text="Ideal for groups that want to do something active together." /><Fact title="3 cocktails included" text="You make and taste several cocktails during the workshop." /><Fact title="Bartender guidance" text="Our bartenders help with flavour, technique and serving." /></div></section>
    <section className="container-premium grid gap-10 pb-24 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Workshop</p><h2 className="h2 mt-4">What you do</h2><p className="mt-6 text-lg leading-[1.65] text-white/72 md:text-xl">Our bartenders walk you through mixing, shaking and garnishing — hands on, no slides, no theory. Every guest makes at least 3 cocktails and drinks what they make. Stay on for the club night after.</p><ul className="mt-8 grid gap-3 text-white/78"><li>• Make several cocktails</li><li>• Work with bar tools, ingredients and glassware</li><li>• Guidance from experienced bartenders</li><li>• Time to have drinks with your group</li></ul></div><div className="grid grid-cols-2 gap-4">{gallery.slice(0,4).map((item)=><div key={item.url} className="photo-tile image-frame aspect-square"><SafeImage src={item.url} fallbackSrc={images.fallbackWide} alt={item.alt} fill sizes="(min-width:1024px) 25vw, 50vw" className="object-cover brightness-[1.08]" /></div>)}</div></section>
    <section className="container-premium pb-24"><div className="max-w-3xl"><p className="eyebrow">Groups</p><h2 className="h2 mt-4">Who it is for</h2><p className="mt-6 text-lg leading-[1.65] text-white/72 md:text-xl">The cocktail workshop is best for groups that want to do something without making it formal. Think bachelor and bachelorette parties, company outings, birthdays, team nights or groups of friends starting the evening well.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{groupTypes.map((type)=><article key={type} className="rounded-3xl border border-white/10 bg-white/[0.045] p-6"><h3 className="text-2xl font-black tracking-[-0.03em]">{type}</h3><p className="mt-3 text-white/66">Active, social and easy to combine with drinks or nightlife in Maastricht.</p></article>)}</div></section>
    <section className="container-premium pb-24"><div className="seo-panel grid gap-8 rounded-[2rem] border border-white/10 bg-white/[0.045] p-7 md:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Maastricht</p><h2 className="h2 mt-4">Cocktail workshop in Maastricht</h2></div><div className="prose-premium">{SEO_TEXT.workshop.en.split('\n\n').map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>
    <section className="container-premium pb-24"><p className="eyebrow">FAQ</p><h2 className="h2 mt-4">Frequently asked questions</h2><div className="faq-grid mt-8 grid gap-4 lg:grid-cols-2">{faqs.map((f)=><details key={f.question} className="luxury-panel rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-base leading-7 text-white/72 md:text-lg">{f.answer}</p></details>)}</div></section>
    <section id="inquiry" className="container-premium grid gap-8 pb-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Inquiry</p><h2 className="h2 mt-4">Request workshop</h2><p className="mt-6 text-lg leading-[1.65] text-white/72">Drop us a message. We respond fast and help you plan the full evening.</p></div><InquiryForm type="workshop" sourcePage="/en/cocktail-workshop" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'groupSize',label:'Group size',type:'number'},{name:'message',label:'Message',required:true,placeholder:'Date, group size and any wishes.'}]} /></section><JsonLd data={faqSchema(faqs)} />
  </>
}
function Fact({ title, text }: { title: string; text: string }) { return <article className="rounded-3xl border border-white/10 bg-white/[0.045] p-5"><h2 className="text-2xl font-black tracking-[-0.035em]">{title}</h2><p className="mt-3 text-white/66">{text}</p></article> }
