import Image from 'next/image'
import Link from 'next/link'
import { faqSchema } from '@/lib/seo'
import { images } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import { getPageContent } from '@/lib/admin/public'
import JsonLd from '@/components/ui/JsonLd'
import { workshopFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'

export async function generateMetadata() { return cmsMetadata('workshop', 'en') }
export default async function WorkshopPage() { const content = await getPageContent('cocktail-workshop', 'en'); const pageFaqs = content?.faqs?.length ? content.faqs : faqs; const heroImage = content?.images?.[0]?.url || images.bar; return <><section className="relative min-h-[72vh] pt-36"><Image src={heroImage} alt="Cocktail workshop Maastricht" fill priority sizes="100vw" className="-z-10 object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-transparent"/><div className="container-premium py-24"><p className="eyebrow">Cocktail workshop</p><h1 className="h1 mt-5 max-w-4xl">{content?.heroTitle || 'Cocktail workshop Maastricht.'}</h1><p className="mt-7 max-w-2xl text-xl text-white/70">{content?.heroSubtitle || 'A premium group experience in the heart of Maastricht: hands-on cocktail making, polished hospitality and the kind of atmosphere that turns a workshop into the start of a proper night out.'}</p><Link href="#form" className="btn-primary mt-8">Request workshop</Link></div></section><section className="container-premium py-20 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">From €45 p.p.</p><h2 className="h2 mt-3">Designed for groups that want more than a table reservation.</h2><p className="prose-premium mt-6">Perfect for a bachelorette party in Maastricht, a company team event, birthday or friends weekend. You learn techniques, build flavour, make at least three cocktails and enjoy a social format that feels premium without becoming formal.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Minimum 15 guests','3 cocktails included','Professional bartender','Central Maastricht'].map((x)=><div className="card rounded-3xl p-6" key={x}><h3 className="font-black text-xl">{x}</h3></div>)}</div></section><section id="form" className="container-premium pb-24 grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Inquiry</p><h2 className="h2 mt-3">Plan your workshop.</h2><div className="mt-8 space-y-4">{pageFaqs.map(f=><details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="workshop" sourcePage="/en/cocktail-workshop" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'groupSize',label:'Group size',type:'number'},{name:'message',label:'Message',required:true,placeholder:'Tell us about your group and ideal evening.'}]} /></section><JsonLd data={faqSchema(pageFaqs)} /></> }
