import Image from 'next/image'
import Link from 'next/link'
import { faqSchema } from '@/lib/seo'
import { images } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { cmsMetadata } from '@/lib/pageMetadata'

const faqs = [{ question: 'What does a cocktail workshop cost?', answer: 'From €45 per person based on three cocktails. The owner can manage prices in Sanity.' }, { question: 'What is the minimum group size?', answer: 'The guideline is 15 guests. Smaller groups can contact us for options.' }, { question: 'When can the workshop start?', answer: 'Usually Thursday, Friday or Saturday between 19:00 and 20:30, by arrangement.' }]
export async function generateMetadata() { return cmsMetadata('workshop', 'en') }
export default function WorkshopPage() { return <><section className="relative min-h-[72vh] pt-36"><Image src={images.bar} alt="Cocktail workshop Maastricht" fill priority sizes="100vw" className="-z-10 object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-transparent"/><div className="container-premium py-24"><p className="eyebrow">Cocktail workshop</p><h1 className="h1 mt-5 max-w-4xl">Cocktail workshop Maastricht.</h1><p className="mt-7 max-w-2xl text-xl text-white/70">A hands-on, high-energy group experience led by Cliniq bartenders. Premium, social and made to start the night properly.</p><Link href="#form" className="btn-primary mt-8">Request workshop</Link></div></section><section className="container-premium py-20 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">From €45 p.p.</p><h2 className="h2 mt-3">Designed for groups that want more than a table reservation.</h2><p className="prose-premium mt-6">Perfect for a bachelorette party Maastricht, team event, birthday or friends weekend. Includes bar tools, bartender guidance, three cocktails and the option to stay for nightlife afterwards.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Minimum 15 guests','3 cocktails included','Professional bartender','Central Maastricht'].map((x)=><div className="card rounded-3xl p-6" key={x}><h3 className="font-black text-xl">{x}</h3></div>)}</div></section><section id="form" className="container-premium pb-24 grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Inquiry</p><h2 className="h2 mt-3">Plan your workshop.</h2><div className="mt-8 space-y-4">{faqs.map(f=><details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="workshop" sourcePage="/en/cocktail-workshop" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'preferredDate',label:'Preferred date',type:'date'},{name:'groupSize',label:'Group size',type:'number'},{name:'message',label:'Message',required:true,placeholder:'Tell us about your group and ideal evening.'}]} /></section><JsonLd data={faqSchema(faqs)} /></> }
