import { defineField, defineType } from 'sanity'
export default defineType({ name:'agendaEvent', title:'Events Manager', type:'document', groups:[{ name:'quick', title:'2-minute event setup', default:true },{ name:'content', title:'Content' },{ name:'media', title:'Media' },{ name:'tickets', title:'Tickets & publishing' }], fields:[
  defineField({ name:'title', title:'Event title', type:'string', group:'quick', validation:r=>r.required() }),
  defineField({ name:'subtitle', title:'Subtitle', type:'string', group:'quick' }),
  defineField({ name:'slug', title:'Slug', type:'slug', options:{ source:'title' }, group:'content' }),
  defineField({ name:'date', title:'Event date', type:'date', group:'quick', validation:r=>r.required() }),
  defineField({ name:'startTime', title:'Opening time', type:'string', initialValue:'22:00', group:'quick' }),
  defineField({ name:'endTime', title:'Closing time', type:'string', initialValue:'03:00', group:'quick' }),
  defineField({ name:'ageLimit', title:'Age limit', type:'string', initialValue:'21+', group:'quick' }),
  defineField({ name:'poster', title:'Upload poster', type:'image', options:{ hotspot:true }, group:'quick', fields:[{ name:'alt', title:'Alt text', type:'string' }, { name:'brightness', title:'Brightness control', type:'number', initialValue:1 }] }),
  defineField({ name:'mediaPoster', title:'Poster from Media Library', type:'reference', to:[{ type:'mediaAsset' }], group:'media' }),
  defineField({ name:'gallery', title:'Event gallery images', type:'array', of:[{ type:'reference', to:[{ type:'mediaAsset' }] }], group:'media' }),

  defineField({ name:'titleNl', title:'Dutch title', type:'string', group:'content' }),
  defineField({ name:'titleEn', title:'English title', type:'string', group:'content' }),
  defineField({ name:'subtitleNl', title:'Dutch subtitle', type:'string', group:'content' }),
  defineField({ name:'subtitleEn', title:'English subtitle', type:'string', group:'content' }),
  defineField({ name:'shortDescriptionNl', title:'Dutch short description', type:'text', rows:2, group:'content' }),
  defineField({ name:'shortDescriptionEn', title:'English short description', type:'text', rows:2, group:'content' }),
  defineField({ name:'fullDescriptionNl', title:'Dutch full description', type:'array', of:[{ type:'block' }], group:'content' }),
  defineField({ name:'fullDescriptionEn', title:'English full description', type:'array', of:[{ type:'block' }], group:'content' }),
  defineField({ name:'shortDescription', title:'Short description (legacy fallback)', type:'text', rows:2, group:'content' }),
  defineField({ name:'fullDescription', title:'Full description', type:'array', of:[{ type:'block' }], group:'content' }),
  defineField({ name:'ticketUrl', title:'Ticket / RSVP link', type:'url', group:'tickets' }),
  defineField({ name:'recurring', title:'Recurring event support', type:'object', group:'tickets', fields:[{ name:'enabled', title:'Repeats', type:'boolean' }, { name:'frequency', title:'Frequency', type:'string', options:{ list:['weekly','monthly','custom'] } }, { name:'note', title:'Internal note', type:'string' }] }),
  defineField({ name:'featured', title:'Featured event', type:'boolean', initialValue:false, group:'tickets' }),
  defineField({ name:'published', title:'Published', type:'boolean', initialValue:true, group:'quick' }),
  defineField({ name:'status', title:'Legacy visibility status', type:'string', hidden:true, options:{ list:['draft','published'] }, initialValue:'published' }),
], preview:{ select:{ title:'title', subtitle:'date', media:'poster' } } })
