import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'event',
  title: 'Event',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Event name',
      description: 'The night\'s own name as shown on cards and the detail page heading (e.g. "Amphitryon Inkom Party"). For a plain weekly club night with no name of its own, the DJ\'s name below is used instead - do not put the DJ\'s name here if the event also has its own name.',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: (doc: any) => `${doc.date || ''}-${doc.title || ''}` }, validation: (Rule: any) => Rule.required() }),
    defineField({ name: 'date', title: 'Date', type: 'date', validation: (Rule: any) => Rule.required() }),
    defineField({ name: 'dj', title: 'DJ / act (shown as a secondary "met {DJ}" line under the event name)', type: 'reference', to: [{ type: 'dj' }] }),
    defineField({ name: 'customTitleNl', title: 'Custom title NL', type: 'string' }),
    defineField({ name: 'customTitleEn', title: 'Custom title EN', type: 'string' }),
    defineField({ name: 'eventType', title: 'Event type', type: 'string', initialValue: 'regular', options: { list: [
      { title: 'Regular', value: 'regular' },
      { title: 'Featured', value: 'featured' },
      { title: 'Special', value: 'special' },
      { title: 'Private', value: 'private' },
    ] } }),
    defineField({ name: 'openingTime', title: 'Opening time', type: 'string', initialValue: '22:00' }),
    defineField({ name: 'closingTime', title: 'Closing time', type: 'string', initialValue: '03:00' }),
    defineField({ name: 'minimumAge', title: 'Minimum age', type: 'string', initialValue: '21+' }),
    defineField({ name: 'published', title: 'Published', type: 'boolean', initialValue: true }),
    defineField({ name: 'featured', title: 'Featured', type: 'boolean', initialValue: false }),
    defineField({ name: 'showDetailPage', title: 'Show detail page', type: 'boolean', initialValue: false }),
    defineField({ name: 'eventImage', title: 'Custom event image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'descriptionNl', title: 'Description NL (short teaser, shown on agenda cards)', type: 'text', rows: 4 }),
    defineField({ name: 'descriptionEn', title: 'Description EN (short teaser, shown on agenda cards)', type: 'text', rows: 4 }),
    defineField({
      name: 'promoNl',
      title: 'Promo copy NL (full detail-page body, featured events only)',
      description: 'The full hand-written paragraph shown on this event\'s own detail page. Only used when "Featured" is on - non-featured nights use the short Description above instead. Leave empty and the detail page shows a plain factual line (date/doors/age) instead of guessing.',
      type: 'text',
      rows: 6,
    }),
    defineField({
      name: 'promoEn',
      title: 'Promo copy EN (full detail-page body, featured events only)',
      description: 'English translation of Promo copy NL, same rules.',
      type: 'text',
      rows: 6,
    }),
    defineField({ name: 'ticketUrl', title: 'Ticket/detail URL', type: 'url' }),
    defineField({ name: 'album', title: 'Related album', type: 'reference', to: [{ type: 'album' }] }),
    defineField({
      name: 'metaTitleNl',
      title: 'Meta title NL (detail page <title>, featured events only)',
      description: 'Leave empty to auto-generate "{event name} — {date} | Uitgaan Maastricht CLINIQ" instead.',
      type: 'string',
    }),
    defineField({
      name: 'metaTitleEn',
      title: 'Meta title EN (detail page <title>, featured events only)',
      description: 'Leave empty to auto-generate "{event name} — {date} | Nightlife Maastricht CLINIQ" instead.',
      type: 'string',
    }),
    defineField({
      name: 'metaDescriptionNl',
      title: 'Meta description NL (featured events only)',
      description: 'Leave empty to fall back to the short Description NL above, then to a plain factual line.',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'metaDescriptionEn',
      title: 'Meta description EN (featured events only)',
      description: 'Leave empty to fall back to the short Description EN above, then to a plain factual line.',
      type: 'text',
      rows: 3,
    }),
  ],
  preview: { select: { title: 'title', subtitle: 'date', media: 'eventImage' } },
})
