import Image from 'next/image'
import { metadata as createMetadata, faqSchema } from '@/lib/seo'
import { images, pages } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'

const faqs = [{ question: 'Kan ik de ruimte exclusief huren?', answer: 'Ja, Cliniq is beschikbaar voor exclusieve private events afhankelijk van datum, groepsgrootte en programma.' }, { question: 'Voor hoeveel gasten is Cliniq geschikt?', answer: 'De venue is geschikt voor intieme borrels tot grotere club- en feestconcepten. Capaciteit is instelbaar in Sanity.' }, { question: 'Kunnen jullie DJ, licht en cocktails verzorgen?', answer: 'Ja. Sound, licht, DJ mogelijkheden, barservice en cocktail opties kunnen in één voorstel worden meegenomen.' }]
export const metadata = createMetadata(pages[3].title, pages[3].description, '/event-space')
export default function EventSpacePage(){return <>
<section className="relative min-h-[78vh] pt-36"><Image src={images.crowd} alt="Event space en feestzaal Cliniq Maastricht" fill priority sizes="100vw" className="-z-10 object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-burgundy/30"/><div className="container-premium py-24"><p className="eyebrow">Ruimte huren Maastricht</p><h1 className="h1 mt-5 max-w-5xl">Event space voor feesten met impact.</h1><p className="mt-7 max-w-2xl text-xl text-white/70">Zoek je een feestzaal, zaal huren of private event locatie in Maastricht? Cliniq combineert clubenergie met premium hospitality.</p><a href="#aanvraag" className="btn-primary mt-8">Vrijblijvende aanvraag</a></div></section>
<section className="container-premium py-20"><div className="grid gap-4 md:grid-cols-4">{['Bedrijfsfeest','Verjaardag','Vrijgezellenfeest','Gala','Studentenfeest','Private party','Borrel','Product launch'].map(x=><div key={x} className="card rounded-3xl p-6 font-black text-xl">{x}</div>)}</div></section>
<section className="container-premium grid gap-8 pb-20 lg:grid-cols-2"><div><p className="eyebrow">Faciliteiten</p><h2 className="h2 mt-3">Alles voor jouw event.</h2><p className="prose-premium mt-6">Sound, licht, DJ booth, bar, cocktails, hospitality team, garderobe opties en flexibele indeling. Ideaal voor bedrijfsfeest Maastricht, feestlocatie Maastricht en zaal huren Maastricht.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Club sound & licht','DJ mogelijkheden','Cocktailbar','Centrumlocatie','Branding opties','Hospitality team'].map(x=><div className="card rounded-3xl p-6" key={x}>{x}</div>)}</div></section>
<section className="container-premium pb-20"><div className="grid gap-4 md:grid-cols-3">{[images.crowd,images.club,images.bar].map((src,i)=><div key={src} className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src={src} alt={`Event space Maastricht foto ${i+1}`} fill sizes="33vw" className="object-cover"/></div>)}</div></section>
<section id="aanvraag" className="container-premium grid gap-8 pb-24 lg:grid-cols-2"><div><p className="eyebrow">Aanvraag</p><h2 className="h2 mt-3">Vertel ons je plannen.</h2><div className="mt-8 space-y-4">{faqs.map(f=><details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="event-space" fields={[{name:'name',label:'Naam',required:true},{name:'email',label:'E-mail',type:'email',required:true},{name:'phone',label:'Telefoon'},{name:'eventType',label:'Type event',options:['Bedrijfsfeest','Verjaardag','Vrijgezellenfeest','Gala','Studentenfeest','Private party','Borrel','Product launch']},{name:'preferredDate',label:'Gewenste datum',type:'date'},{name:'guests',label:'Aantal gasten',type:'number'},{name:'message',label:'Bericht',required:true}]} /></section><JsonLd data={faqSchema(faqs)} /></>}
