import { faqSchema } from '@/lib/seo'
import { images, imageSets } from '@/lib/site'
import InquiryForm from '@/components/forms/InquiryForm'
import { getPageContent } from '@/lib/admin/public'
import JsonLd from '@/components/ui/JsonLd'
import { eventSpaceFaqsNl as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
import SafeImage from '@/components/ui/SafeImage'

export async function generateMetadata() { return cmsMetadata('eventSpace', 'nl') }
export default async function EventSpacePage(){
  const content = await getPageContent('event-space')
  const pageFaqs = content?.faqs?.length ? content.faqs : faqs
  const gallery = content?.images?.length ? content.images : imageSets.eventSpace.map((url) => ({ url, alt: 'Event space Cliniq Maastricht', focalPoint: 'center' }))
  const heroImage = gallery[0]?.url || images.crowd
  return <>
    <section className="relative min-h-[80vh] overflow-hidden pt-36"><SafeImage src={heroImage} fallbackSrc={images.fallbackWide} alt="Event space en feestzaal Cliniq Maastricht" fill priority sizes="100vw" className="-z-10 object-cover brightness-[1.08]" objectPosition={gallery[0]?.focalPoint || 'center'} /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black via-black/70 to-burgundy/25"/><div className="container-premium py-24"><p className="eyebrow">Ruimte huren Maastricht</p><h1 className="h1 mt-5 max-w-5xl">{content?.heroTitle || 'Event space voor feesten met impact.'}</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-white/75">{content?.heroSubtitle || 'Zoek je een feestzaal, ruimte huren of private event locatie in Maastricht die niet voelt als een lege zaal? Cliniq combineert het karakter van een club met professionele hospitality, barservice en een sfeer die direct binnenkomt.'}</p><a href="#aanvraag" className="btn-primary mt-8">Vrijblijvende aanvraag</a></div></section>
    <section className="container-premium py-20"><div className="grid gap-4 md:grid-cols-4">{['Bedrijfsfeest','Verjaardag','Vrijgezellenfeest','Gala','Studentenfeest','Private party','Borrel','Product launch'].map((x)=><div key={x} className="luxury-panel rounded-3xl p-6 text-xl font-black">{x}<p className="mt-2 text-sm font-medium text-white/60">Sfeer, bar en techniek al aanwezig.</p></div>)}</div></section>
    <section className="container-premium grid gap-10 pb-20 lg:grid-cols-2"><div><p className="eyebrow">Faciliteiten</p><h2 className="h2 mt-3">Alles voor een avond die klopt.</h2><p className="prose-premium mt-6">Van sound en licht tot DJ booth, cocktailbar, ontvangst, garderobe-opties en flexibele indeling: Cliniq is gebouwd voor events die energie nodig hebben. Ideaal voor bedrijfsfeest Maastricht, feestzaal Maastricht, verjaardag vieren Maastricht, vrijgezellenfeest en private party.</p></div><div className="grid gap-4 sm:grid-cols-2">{['Club sound & licht','DJ mogelijkheden','Cocktailbar','Centrumlocatie','Branding opties','Hospitality team'].map((x)=><div className="luxury-panel rounded-3xl p-6" key={x}><h3 className="font-black">{x}</h3><p className="mt-2 text-sm text-white/60">Afgestemd op jouw groep, planning en gewenste sfeer.</p></div>)}</div></section>
    <section className="container-premium pb-20"><div className="grid gap-4 md:grid-cols-[1fr_.8fr_1fr]">{gallery.slice(0,3).map((item,i)=><div key={`${item.url}-${i}`} className={`image-frame ${i === 1 ? 'md:mt-12' : ''} aspect-[4/5]`}><SafeImage src={item.url} fallbackSrc={images.fallbackWide} alt={item.alt || `Event space Maastricht foto ${i+1}`} fill sizes="33vw" className="object-cover brightness-[1.08]" objectPosition={item.focalPoint || 'center'} /></div>)}</div></section>
    <section id="aanvraag" className="container-premium grid gap-8 pb-24 lg:grid-cols-2"><div><p className="eyebrow">Aanvraag</p><h2 className="h2 mt-3">Vertel ons je plannen.</h2><div className="mt-8 space-y-4">{pageFaqs.map((f)=><details key={f.question} className="luxury-panel rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><InquiryForm type="event-space" fields={[{name:'name',label:'Naam',required:true},{name:'email',label:'E-mail',type:'email',required:true},{name:'phone',label:'Telefoon'},{name:'eventType',label:'Type event',options:['Bedrijfsfeest','Verjaardag','Vrijgezellenfeest','Gala','Studentenfeest','Private party','Borrel','Product launch']},{name:'preferredDate',label:'Gewenste datum',type:'date'},{name:'guests',label:'Aantal gasten',type:'number'},{name:'message',label:'Bericht',required:true}]} /></section><JsonLd data={faqSchema(pageFaqs)} />
  </>
}
