import Link from 'next/link'
import { images, site } from '@/lib/site'
import { getSiteSettings } from '@/lib/admin/public'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { faqSchema } from '@/lib/seo'
import { contactFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
import SafeImage from '@/components/ui/SafeImage'
export async function generateMetadata() { return cmsMetadata('contact', 'en') }
export default async function ContactPage(){ const settings = await getSiteSettings(); return <section className="container-premium pt-36 pb-24"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><h1 className="h1">Contact</h1><p className="mt-7 max-w-xl text-2xl font-bold leading-tight text-white/78">Questions about the agenda, a workshop or hiring CLINIQ? Contact us.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" href={`mailto:${settings.email || site.email}`}>Contact us</Link><Link className="btn-secondary" href="/en/cocktail-workshop">Request workshop</Link></div></div><div className="image-frame aspect-[4/3]"><SafeImage src={images.contactInterior} fallbackSrc={images.fallbackWide} alt="Interior of CLINIQ Maastricht" fill priority sizes="55vw" className="object-cover brightness-[1.08]" /></div></div><div className="mt-12 grid gap-8 lg:grid-cols-2"><div className="space-y-6"><div className="card rounded-[2rem] p-8"><h2 className="h3">CLINIQ Maastricht</h2><p className="mt-4 text-white/70">{settings.address || `${site.address.street}, ${site.address.postalCode} ${site.address.city}`}</p><p className="mt-4"><a href={`tel:${settings.phone || site.phone}`}>{settings.phone || site.phone}</a><br/><a href={`mailto:${settings.email || site.email}`}>{settings.email || site.email}</a></p></div><div className="card overflow-hidden rounded-[2rem]"><iframe title="Route to CLINIQ Maastricht" src={site.maps} className="h-80 w-full border-0" loading="lazy"/></div></div><InquiryForm type="contact" sourcePage="/en/contact" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'message',label:'Message',required:true}]} /></div><div className="mt-14"><h2 className="eyebrow">Practical</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{faqs.map(f => <details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><JsonLd data={faqSchema(faqs)} /></section>}
