import Link from 'next/link'
import { site } from '@/lib/site'
import { getSiteSettings } from '@/lib/admin/public'
import InquiryForm from '@/components/forms/InquiryForm'
import JsonLd from '@/components/ui/JsonLd'
import { faqSchema } from '@/lib/seo'
import { contactFaqsEn as faqs } from '@/lib/faqs'
import { cmsMetadata } from '@/lib/pageMetadata'
export async function generateMetadata() { return cmsMetadata('contact', 'en') }
export default async function ContactPage(){ const settings = await getSiteSettings(); return <section className="container-premium pt-36 pb-24"><p className="eyebrow">Contact</p><h1 className="h1 mt-5">Contact Cliniq Maastricht.</h1><div className="mt-12 grid gap-8 lg:grid-cols-2"><div className="space-y-6"><div className="card rounded-[2rem] p-8"><h2 className="h3">Cliniq Maastricht</h2><p className="mt-4 text-white/70">{settings.address || `${site.address.street}, ${site.address.postalCode} ${site.address.city}`}</p><p className="mt-4"><a href={`tel:${settings.phone || site.phone}`}>{settings.phone || site.phone}</a><br/><a href={`mailto:${settings.email || site.email}`}>{settings.email || site.email}</a></p><div className="mt-6 flex gap-3"><Link className="btn-primary" href="/en/nightlife">Agenda</Link><Link className="btn-secondary" href="/en/event-space">Venue hire</Link></div></div><div className="card overflow-hidden rounded-[2rem]"><iframe title="Route to Cliniq Maastricht" src={site.maps} className="h-80 w-full border-0" loading="lazy"/></div></div><InquiryForm type="contact" sourcePage="/en/contact" fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'phone',label:'Phone'},{name:'message',label:'Message',required:true}]} /></div><div className="mt-14"><h2 className="h2">Helpful answers.</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{faqs.map(f => <details key={f.question} className="card rounded-2xl p-5"><summary className="cursor-pointer font-black">{f.question}</summary><p className="mt-3 text-white/70">{f.answer}</p></details>)}</div></div><JsonLd data={faqSchema(faqs)} /></section>}
